### ISSUE TITLE
java.io.IOException: Cannot run program "pythonw"

### ISSUE THREAD

**Issue by jmashore** [wakatime/jetbrains-wakatime#103]
Since around the 1st of the month I've been getting this error any ideas ? :

INFO - pi.util.registry.RegistryState -   dumb.aware.run.configurations = true 
2018-06-04 16:15:35,484 [   6813]   INFO - com.intellij.ide.ui.UISettings - Loaded: fontSize=12, fontScale=0.0; restored: fontSize=12, fontScale=1.0 
2018-06-04 16:15:36,467 [   7796]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.ide.ui.OptionsTopHitProvider$Activity@50b4a144 
2018-06-04 16:15:36,552 [   7881]   INFO - til.net.ssl.CertificateManager - Default SSL context initialized 
2018-06-04 16:15:36,866 [   8195]   INFO - rains.ide.BuiltInServerManager - built-in server started, port 63342 
2018-06-04 16:15:36,974 [   8303]   INFO - gs.impl.UpdateCheckerComponent - channel: release 
2018-06-04 16:15:37,405 [   8734]   INFO - ction.BrowserConnectionManager - Browser connected: version 2.0.9, Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36 
2018-06-04 16:15:37,421 [   8750]   INFO - il.indexing.FileBasedIndexImpl - Index exts enumerated:183 
2018-06-04 16:15:37,434 [   8763]   INFO - il.indexing.FileBasedIndexImpl - Index scheduled:12 
2018-06-04 16:15:37,547 [   8876]   INFO - tellij.psi.stubs.StubIndexImpl - All stub exts enumerated:99 
2018-06-04 16:15:37,547 [   8876]   INFO - tellij.psi.stubs.StubIndexImpl - stub exts update scheduled:1 
2018-06-04 16:15:37,750 [   9079]   INFO -                       WakaTime - Initializing WakaTime plugin v9.2.0 (https://wakatime.com/) 
2018-06-04 16:15:37,754 [   9083]  DEBUG -                       WakaTime - Logging level set to DEBUG 
2018-06-04 16:15:37,895 [   9224]  DEBUG -                       WakaTime -  
com.sun.jna.platform.win32.Win32Exception: The system cannot find the file specified.
	at com.sun.jna.platform.win32.Advapi32Util.registryGetKeys(Advapi32Util.java:1569)
	at com.wakatime.intellij.plugin.Dependencies.getPythonFromRegistry(Dependencies.java:115)
	at com.wakatime.intellij.plugin.Dependencies.getPythonLocation(Dependencies.java:83)
	at com.wakatime.intellij.plugin.Dependencies.isPythonInstalled(Dependencies.java:45)
	at com.wakatime.intellij.plugin.WakaTime.initComponent(WakaTime.java:87)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:497)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:119)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:454)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:103)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:406)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:392)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:65)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:346)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2018-06-04 16:15:37,902 [   9231]  DEBUG -                       WakaTime -  
com.sun.jna.platform.win32.Win32Exception: The system cannot find the file specified.
	at com.sun.jna.platform.win32.Advapi32Util.registryGetKeys(Advapi32Util.java:1569)
	at com.wakatime.intellij.plugin.Dependencies.getPythonFromRegistry(Dependencies.java:127)
	at com.wakatime.intellij.plugin.Dependencies.getPythonLocation(Dependencies.java:83)
	at com.wakatime.intellij.plugin.Dependencies.isPythonInstalled(Dependencies.java:45)
	at com.wakatime.intellij.plugin.WakaTime.initComponent(WakaTime.java:87)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:497)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:119)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:454)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:103)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:406)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:392)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:65)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:346)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2018-06-04 16:15:37,905 [   9234]  DEBUG -                       WakaTime - pythonw --version 
2018-06-04 16:15:37,910 [   9239]  DEBUG -                       WakaTime - java.io.IOException: Cannot run program "pythonw": CreateProcess error=2, The system cannot find the file specified 
2018-06-04 16:15:37,910 [   9239]  DEBUG -                       WakaTime - python3 --version 
2018-06-04 16:15:37,911 [   9240]  DEBUG -                       WakaTime - java.io.IOException: Cannot run program "python3": CreateProcess error=2, The system cannot find the file specified 
2018-06-04 16:15:37,911 [   9240]  DEBUG -                       WakaTime - python --version 
2018-06-04 16:15:37,934 [   9263]  DEBUG -                       WakaTime - java.io.IOException: Cannot run program "python": CreateProcess error=2, The system cannot find the file specified 
2018-06-04 16:15:37,934 [   9263]  DEBUG -                       WakaTime - \pythonw --version 
2018-06-04 16:15:37,934 [   9263]  DEBUG -                       WakaTime - java.io.IOException: Cannot run program "\pythonw": CreateProcess error=2, The system cannot find the file specified 
2018-06-04 16:15:37,934 [   9263]  DEBUG -                       WakaTime - \python3 --version 
2018-06-04 16:15:37,934 [   9263]  DEBUG -                       WakaTime - java.io.IOException: Cannot run program "\python3": CreateProcess error=2, The system cannot find the file specified 
2018-06-04 16:15:37,934 [   9263]  DEBUG -                       WakaTime - \python --version 
2018-06-04 16:15:37,934 [   9263]  DEBUG -                       WakaTime - java.io.IOException: Cannot run program "\python": CreateProcess error=2, The system cannot find the file specified 
2018-06-04 16:15:37,944 [   9273]  DEBUG -                       WakaTime - \usr\local\bin\pythonw --version 
2018-06-04 16:15:37,946 [   9275]  DEBUG -                       WakaTime - java.io.IOException: Cannot run program "\usr\local\bin\pythonw": CreateProcess error=2, The system cannot find the file specified 
2018-06-04 16:15:37,946 [   9275]  DEBUG -                       WakaTime - \usr\local\bin\python3 --version 
2018-06-04 16:15:37,948 [   9277]  DEBUG -                       WakaTime - java.io.IOException: Cannot run program "\usr\local\bin\python3": CreateProcess error=2, The system cannot find the file specified 
2018-06-04 16:15:37,948 [   9277]  DEBUG -                       WakaTime - \usr\local\bin\python --version 
2018-06-04 16:15:37,950 [   9279]  DEBUG -                       WakaTime - java.io.IOException: Cannot run program "\usr\local\bin\python": CreateProcess error=2, The system cannot find the file specified 
2018-06-04 16:15:37,950 [   9279]  DEBUG -                       WakaTime - \usr\bin\pythonw --version 
2018-06-04 16:15:37,951 [   9280]  DEBUG -                       WakaTime - java.io.IOException: Cannot run program "\usr\bin\pythonw": CreateProcess error=2, The system cannot find the file specified 
2018-06-04 16:15:37,951 [   9280]  DEBUG -                       WakaTime - \usr\bin\python3 --version 
2018-06-04 16:15:37,951 [   9280]  DEBUG -                       WakaTime - java.io.IOException: Cannot run program "\usr\bin\python3": CreateProcess error=2, The system cannot find the file specified 
2018-06-04 16:15:37,951 [   9280]  DEBUG -                       WakaTime - \usr\bin\python --version 
2018-06-04 16:15:37,951 [   9280]  DEBUG -                       WakaTime - java.io.IOException: Cannot run program "\usr\bin\python": CreateProcess error=2, The system cannot find the file specified 
2018-06-04 16:15:37,951 [   9280]  DEBUG -                       WakaTime - C:\Users\jmash\AppData\Roaming\WakaTime\python\pythonw --version 
2018-06-04 16:15:37,957 [   9286]  DEBUG -                       WakaTime - java.io.IOException: Cannot run program "C:\Users\jmash\AppData\Roaming\WakaTime\python\pythonw": CreateProcess error=2, The system cannot find the file specified 
2018-06-04 16:15:37,957 [   9286]  DEBUG -                       WakaTime - C:\Users\jmash\AppData\Roaming\WakaTime\python\python3 --version 
2018-06-04 16:15:37,959 [   9288]  DEBUG -                       WakaTime - java.io.IOException: Cannot run program "C:\Users\jmash\AppData\Roaming\WakaTime\python\python3": CreateProcess error=2, The system cannot find the file specified 
2018-06-04 16:15:37,959 [   9288]  DEBUG -                       WakaTime - C:\Users\jmash\AppData\Roaming\WakaTime\python\python --version 
2018-06-04 16:15:37,961 [   9290]  DEBUG -                       WakaTime - java.io.IOException: Cannot run program "C:\Users\jmash\AppData\Roaming\WakaTime\python\python": CreateProcess error=2, The system cannot find the file specified 
2018-06-04 16:15:37,961 [   9290]  DEBUG -                       WakaTime - pythonw --version 
2018-06-04 16:15:37,965 [   9294]  DEBUG -                       WakaTime - java.io.IOException: Cannot run program "pythonw": CreateProcess error=2, The system cannot find the file specified 
2018-06-04 16:15:37,965 [   9294]  DEBUG -                       WakaTime - python3 --version 
2018-06-04 16:15:37,971 [   9300]  DEBUG -                       WakaTime - java.io.IOException: Cannot run program "python3": CreateProcess error=2, The system cannot find the file specified 
2018-06-04 16:15:37,971 [   9300]  DEBUG -                       WakaTime - python --version 
2018-06-04 16:15:37,975 [   9304]  DEBUG -                       WakaTime - java.io.IOException: Cannot run program "python": CreateProcess error=2, The system cannot find the file specified 
2018-06-04 16:15:37,976 [   9305]  DEBUG -                       WakaTime - C:\Users\jmash\.windows-build-tools\python27\pythonw --version 
2018-06-04 16:15:38,029 [   9358]  DEBUG -                       WakaTime - Python 2.7.14 
2018-06-04 16:15:38,029 [   9358]  DEBUG -                       WakaTime - Found python binary: C:\Users\jmash\.windows-build-tools\python27\pythonw 
2018-06-04 16:15:38,070 [   9399]   INFO - ndex.PrebuiltIndexProviderBase - Using prebuilt id-index from C:\Users\jmash\.PhpStorm2017.3\system\index\.persistent\prebuilt\PHP\id-index.input 
2018-06-04 16:15:39,919

**Comment by alanhamlett** [comment]
Those are just debug messages while the plugin looks for a working Python version. If you turn off debug mode they should go away. Are there other errors besides the debug messages or symptoms of the plugin not working?

**Comment by jmashore** [comment]
No other symptons per se. It just stopped logging everything around June 1st. I believe there was a windows update around that time too (not for sure). I've tried restarting the machine still no good. Wondering if I should try removing and reinstalling the pluggin. It was working GREAT !

**Comment by jmashore** [comment]
I've removed and reinstalled the wakatime pluggin from PHP Storm  running on Windows 10 recently updated with a Microsoft patch. This seems to have cured the issue. Whether or not the re-install of Python was necessary is unknown. 

PhpStorm 2017.3.3
Build #PS-173.4301.34, built on January 18, 2018
JRE: 1.8.0_152-release-1024-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
