### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by eevahr** [wakatime/jetbrains-wakatime#126]
The extension seems to work fine but it told me to report so here i am.

Don't really know how to reproduce this, it just happened.

<details><summary>Stacktrace</summary>
<pre>
java.lang.NullPointerException
	at com.intellij.ui.messages.SheetMessage.<init>(SheetMessage.java:78)
	at com.intellij.ui.messages.JBMacMessages.showErrorDialog(JBMacMessages.java:189)
	at com.intellij.openapi.ui.Messages.showWarningDialog(Messages.java:891)
	at com.wakatime.intellij.plugin.WakaTime.checkDebug(WakaTime.java:214)
	at com.wakatime.intellij.plugin.WakaTime.initComponent(WakaTime.java:93)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:503)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$load$7(ApplicationImpl.java:414)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:414)
	at com.intellij.idea.IdeaApplication.lambda$executeInitAppInEdt$5(IdeaApplication.java:150)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:438)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
</pre>
</details>

**Comment by alanhamlett** [comment]
That shouldn't happen, since we catch `NullPointerException` when showing the debug warning message:
https://github.com/wakatime/jetbrains-wakatime/blob/1f53a99a1ad3d513bd6eeacde413b10d5d389b1d/src/com/wakatime/intellij/plugin/WakaTime.java#L215

Just to make sure, I've released a new version of the plugin that catches all exceptions.

Also, this `NullPointerException` won't happen if WakaTime's debug mode is turned off.
