### ISSUE TITLE
Pycharm with anaconda on macOS not working 

### ISSUE THREAD

**Issue by hubingzhi** [wakatime/jetbrains-wakatime#136]
2020-03-04 13:52:25,587 [   1536]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: WakaTime (11.0.0) 
2020-03-04 13:52:26,158 [   2107]   INFO -                       WakaTime - Initializing WakaTime plugin v11.0.0 (https://wakatime.com/) 
2020-03-04 13:52:26,162 [   2111]   INFO -                       WakaTime - Finished initializing WakaTime plugin 
2020-03-04 13:52:26,165 [   2114]   WARN -                       WakaTime - Cannot run program "/Users/hbz/.wakatime/wakatime-cli/wakatime-cli": error=13, Permission denied 
java.io.IOException: Cannot run program "/Users/hbz/.wakatime/wakatime-cli/wakatime-cli": error=13, Permission denied
	at com.wakatime.intellij.plugin.Dependencies.isCLIOld(Dependencies.java:84)
	at com.wakatime.intellij.plugin.WakaTime$1.run(WakaTime.java:99)
2020-03-04 13:52:26,168 [   2117]   INFO -                       WakaTime - Upgrading wakatime-cli ... 
2020-03-04 13:56:55,182 [ 271131]  DEBUG -                       WakaTime - Logging level set to DEBUG 
2020-03-04 14:00:30,955 [   2395]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: WakaTime (11.0.0) 
2020-03-04 14:00:31,469 [   2909]   INFO -                       WakaTime - Initializing WakaTime plugin v11.0.0 (https://wakatime.com/) 
2020-03-04 14:00:31,470 [   2910]  DEBUG -                       WakaTime - Logging level set to DEBUG 
2020-03-04 14:00:31,475 [   2915]  DEBUG -                       WakaTime - wakatime-cli local version output: "" 
2020-03-04 14:00:31,476 [   2916]  DEBUG -                       WakaTime - wakatime-cli local version exit code: 137 
2020-03-04 14:00:31,476 [   2916]   INFO -                       WakaTime - Upgrading wakatime-cli ... 
	at com.wakatime.intellij.plugin.WakaTime.checkDebug(WakaTime.java:179)
	at com.wakatime.intellij.plugin.WakaTime.initComponent(WakaTime.java:87)
2020-03-04 14:00:31,652 [   3092]  ERROR - m.intellij.openapi.ui.Messages - Plugin to blame: WakaTime version: 11.0.0 
	at com.wakatime.intellij.plugin.WakaTime.checkDebug(WakaTime.java:179)
	at com.wakatime.intellij.plugin.WakaTime.initComponent(WakaTime.java:87)
2020-03-04 14:00:31,668 [   3108]  ERROR - i.messages.MessagesServiceImpl - Plugin to blame: WakaTime version: 11.0.0 
2020-03-04 14:00:35,025 [   6465]   INFO -                       WakaTime - Finished initializing WakaTime plugin 
2020-03-04 14:00:35,104 [   6544]  DEBUG -                       WakaTime - Api Key: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX1991 

i tried pyopenssl, add permission still not working. thank you.

**Comment by hubingzhi** [comment]
downloaded wakatime with conda install -c .. then restart my mac.. then it worked. 
Not sure if this is the reason.
