### ISSUE TITLE
Wakatime doesn't work with my Pycharm

### ISSUE THREAD

**Issue by KevinChen1994** [wakatime/jetbrains-wakatime#141]
My Pycharm version is 2019.3. wakatime version is 11.0.1

This is my debug log. Please help me to solve this issue thanks!

`2020-04-08 17:58:10,950 [ 938744]   WARN -                       WakaTime - Unexpected end of ZLIB input stream 
	at com.wakatime.intellij.plugin.Dependencies.unzip(Dependencies.java:304)
	at com.wakatime.intellij.plugin.Dependencies.installCLI(Dependencies.java:148)
	at com.wakatime.intellij.plugin.WakaTime$1.run(WakaTime.java:93)
2020-04-08 17:58:10,951 [ 938745]   INFO -                       WakaTime - Finished downloading and installing wakatime-cli. 
2020-04-08 17:58:10,951 [ 938745]  DEBUG -                       WakaTime - CLI location: /Users/chenmeng/.wakatime/wakatime-cli/wakatime-cli 
2020-04-08 17:58:38,103 [ 965897]  DEBUG -                       WakaTime - Executing CLI: [/Users/chenmeng/.wakatime/wakatime-cli/wakatime-cli, --entity, /Users/chenmeng/PycharmProjects/leetcode-algorithm/code/146.py, --time, 1586338972.8880, --key, XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX7c8e, --project, leetcode-algorithm, --language, Python, --plugin, Python/2019.3.4 Python-wakatime/11.0.1, --extra-heartbeats] 
2020-04-08 17:58:38,110 [ 965904]   WARN -                       WakaTime - Cannot run program "/Users/chenmeng/.wakatime/wakatime-cli/wakatime-cli": error=2, No such file or directory 
java.io.IOException: Cannot run program "/Users/chenmeng/.wakatime/wakatime-cli/wakatime-cli": error=2, No such file or directory
	at com.wakatime.intellij.plugin.WakaTime.sendHeartbeat(WakaTime.java:231)
	at com.wakatime.intellij.plugin.WakaTime.processHeartbeatQueue(WakaTime.java:223)
	at com.wakatime.intellij.plugin.WakaTime.access$100(WakaTime.java:46)
	at com.wakatime.intellij.plugin.WakaTime$4.run(WakaTime.java:151)
`

**Comment by KevinChen1994** [comment]
I did't change anything, but today it works!
