### ISSUE TITLE
Proxy string formatting error in GoLand 2020.2 EAP

### ISSUE THREAD

**Issue by blujio** [wakatime/jetbrains-wakatime#143]
I switch to EAP version of Goland and get the following stacktrace when a project loads.  It is persistent and has shown up after a few os updates as well as reboots.

**WakaTime Plugin Version:**  11.0.1

**Goland IDE Version:** 
GoLand 2020.2 EAP
Build #GO-202.4357.28, built on May 28, 2020
GoLand EAP User
Expiration date: June 27, 2020
Runtime version: 11.0.7+10-b912.1 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 4716M
Cores: 12
Registry: ide.completion.variant.limit=500, debugger.valueTooltipAutoShowOnSelection=true, suggest.all.run.configurations.from.context=true, ide.balloon.shadow.size=0, ideFeaturesTrainer.welcomeScreen.tutorialsTree=TRUE, go.run.processes.with.pty=false
Non-Bundled Plugins: Jenkins Control Plugin, com.wakatime.intellij.plugin, net.seesharpsoft.intellij.plugins.csv

Error showing proxy string must follow a specific format, but I'm not using a proxy nor do I have one configured.   I have the 'No Proxy' option selected in the ide settings.

**Stack Trace:** 
java.lang.Throwable: Proxy string must follow https://user:pass@host:port format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx <actual has my api key in stack trace instead of x's>
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:143)
	at com.wakatime.intellij.plugin.Dependencies.configureProxy(Dependencies.java:282)
	at com.wakatime.intellij.plugin.WakaTime.initComponent(WakaTime.java:79)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:44)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:115)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:62)
	at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:258)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$loadComponents$5(ApplicationImpl.java:346)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:628)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.loadComponents(ApplicationImpl.java:346)
	at com.intellij.idea.ApplicationLoader$startApp$6$loadComponentInEdtFuture$1.run(ApplicationLoader.kt:193)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:816)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:416)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by blujio** [comment]
2020-06-03 11:27:04,165 [  31915]  DEBUG -                       WakaTime - Executing CLI: [/Users/jason.costello/.wakatime/wakatime-cli/wakatime-cli, --entity, /Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/config.csv, --time, 1591201605.1570, --key, XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX285e, --project, catalyst, --language, CSV, --plugin, GoLand/2020.2 EAP GoLand-wakatime/11.0.1, --extra-heartbeats] 
2020-06-03 11:27:04,174 [  31924]  DEBUG -                       WakaTime - [{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/temp.txt","timestamp":1591201605.4060,"is_write":false,"project":"catalyst","language":"PLAIN_TEXT"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/config/skumap.go","timestamp":1591201605.4670,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/server/get_file_by_guid.go","timestamp":1591201605.4860,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/server/collect_activation_files.go","timestamp":1591201605.4870,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/inventory/core.go","timestamp":1591201605.5040,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/server/server.go","timestamp":1591201605.5460,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/server/get_file_by_guid.go","timestamp":1591201605.6170,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/inventory/core_test.go","timestamp":1591201605.6190,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/server/collect_activation_files.go","timestamp":1591201605.6320,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/inventory/core.go","timestamp":1591201605.6660,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/vendor/github.mycompany.com/myorg/sspkgs/corectk/device.go","timestamp":1591201605.6720,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/config/skumap.go","timestamp":1591201605.7020,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/inventory/core.go","timestamp":1591201605.7160,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/server/server.go","timestamp":1591201605.7190,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/inventory/core_test.go","timestamp":1591201605.7220,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/config/skumap.go","timestamp":1591201605.7220,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/vendor/github.mycompany.com/myorg/sspkgs/corectk/device.go","timestamp":1591201605.7480,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/config/skumap_test.go","timestamp":1591201605.7490,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/vendor/github.mycompany.com/myorg/sspkgs/corectk/device.go","timestamp":1591201605.7620,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/main.go","timestamp":1591201605.7650,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/inventory/core.go","timestamp":1591201605.8690,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/inventory/core_test.go","timestamp":1591201605.9200,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/inventory/core.go","timestamp":1591201606.3900,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/inventory/core_test.go","timestamp":1591201606.3910,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/inventory/core.go","timestamp":1591201606.6920,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/inventory/core_test.go","timestamp":1591201606.6940,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/config/skumap_test.go","timestamp":1591201606.8620,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/inventory/core.go","timestamp":1591201607.1120,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/inventory/core_test.go","timestamp":1591201607.1150,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/inventory/core.go","timestamp":1591201607.3100,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/inventory/core_test.go","timestamp":1591201607.3100,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/inventory/core.go","timestamp":1591201607.4160,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/inventory/core_test.go","timestamp":1591201607.4190,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/inventory/core.go","timestamp":1591201607.6570,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/inventory/core_test.go","timestamp":1591201607.6580,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/inventory/core.go","timestamp":1591201607.7130,"is_write":false,"project":"catalyst","language":"Go"},{"entity":"/Users/jason.costello/go/src/github.mycompany.com/myorg/catalyst/inventory/core_test.go","timestamp":1591201607.7130,"is_write":false,"project":"catalyst","language":"Go"}]

**Comment by blujio** [comment]
dammit..let my api key slip in the edit on the first comment.  issued a new one.
