### ISSUE TITLE
it is doesnt work

### ISSUE THREAD

**Issue by susanforme** [wakatime/jetbrains-wakatime#147]
This is my first time using wakatime,but  I encountered these problems
```
        WakaTime - Cannot run program "C:\Users\susan\AppData\Roaming\WakaTime\wakatime-cli\wakatime-cli.exe": CreateProcess error=2, The system can not find the file specified。 
java.io.IOException: Cannot run program "C:\Users\susan\AppData\Roaming\WakaTime\wakatime-cli\wakatime-cli.exe": CreateProcess error=2, The system can not find the file specified。
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:592)
	at java.base/java.lang.Runtime.exec(Runtime.java:451)
	at com.wakatime.intellij.plugin.WakaTime.sendHeartbeat(WakaTime.java:231)
	at com.wakatime.intellij.plugin.WakaTime.processHeartbeatQueue(WakaTime.java:223)
	at com.wakatime.intellij.plugin.WakaTime.access$100(WakaTime.java:46)
	at com.wakatime.intellij.plugin.WakaTime$4.run(WakaTime.java:151)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: CreateProcess error=2,  The system can not find the file specified。
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:478)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 13 more
```

**Comment by susanforme** [comment]
> 这是我第一次使用wakatime，但是遇到了这些问题
> 
> ```
>         WakaTime - Cannot run program "C:\Users\susan\AppData\Roaming\WakaTime\wakatime-cli\wakatime-cli.exe": CreateProcess error=2, The system can not find the file specified。 
> java.io.IOException: Cannot run program "C:\Users\susan\AppData\Roaming\WakaTime\wakatime-cli\wakatime-cli.exe": CreateProcess error=2, The system can not find the file specified。
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
> 	at java.base/java.lang.Runtime.exec(Runtime.java:592)
> 	at java.base/java.lang.Runtime.exec(Runtime.java:451)
> 	at com.wakatime.intellij.plugin.WakaTime.sendHeartbeat(WakaTime.java:231)
> 	at com.wakatime.intellij.plugin.WakaTime.processHeartbeatQueue(WakaTime.java:223)
> 	at com.wakatime.intellij.plugin.WakaTime.access$100(WakaTime.java:46)
> 	at com.wakatime.intellij.plugin.WakaTime$4.run(WakaTime.java:151)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
> 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> Caused by: java.io.IOException: CreateProcess error=2,  The system can not find the file specified。
> 	at java.base/java.lang.ProcessImpl.create(Native Method)
> 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:478)
> 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
> 	... 13 more
> ```

**Comment by alanhamlett** [comment]
Did you get it working, since you've closed the issue?
