### ISSUE TITLE
Logged 24 hrs of coding activity

### ISSUE THREAD

**Issue by spont4e** [wakatime/jetbrains-wakatime#157]
I received this email from WakaTime.
```
Hey there,

We noticed some unusual coding activity from your PhpStorm WakaTime plugin Yesterday:
You have 24 hrs of coding activity.

In rare cases, other PhpStorm extensions can cause problems with WakaTime. Please make sure your other PhpStorm extensions are not simulating cursor movements or saving files in the background. This can trick the WakaTime plugin into thinking you were typing even when you weren’t using your PhpStorm editor.
```
WakaTime: 11.0.1
PHPStorm: 2020.2.4

**Comment by alanhamlett** [comment]
What other extensions do you have installed?

**Comment by spont4e** [comment]
- .env files support (2020.3)
- Ansible (0.92)
- Bootstrap 3 (4.1.1)
- Case conversion (0.7.1)
- Emmet Everywhere (1.2.5)
- GitToolBox (202.2.5)
- Laravel (0.15.4)
- Tailwindcss (1.4.6)
- Translation (3.0)
- WakaTime (11.0.1)
- YAML/Ansible support (0.11.2)
- Database Tools and SQL (202.8194.11)
- Docker (202.8194.11)
- FTP/SFTP Connectivity (ex. Remote Hosts Access) (202.8194.11)
- Vagrant (202.8194.11)
- HTML Tools (202.8194.11)
- Refactor-X (202.8194.11)
- XPathView + XSLT (202.8194.11)
- IDE Settings Sync (202.8194.11)
- Settings Repository (202.8194.11)
- JavaScript and TypeScript (202.8194.11)
- JavaScript Debugger (202.8194.11)
- JavaScript Intention Power Pack (202.8194.11)
- Vue.js (202.8194.11)
- Ini (202.8194.11)
- Markdown (202.8194.11)
- Shell Script (202.8194.11)
- YAML (202.8194.11)
- PHP Docker (202.8194.11)
- PHP Remote Interpreter (202.8194.11)
- Hunspell (202.8194.11)
- CSS (202.8194.11)
- Less (202.8194.11)
- Sass (202.8194.11)
- W3C Validators (202.8194.11)
- Blade (202.8194.11)
- ChangeReminder (202.8194.11)
- Git (202.8194.11)
- Command Line Tool (202.8194.11)
- EditorConfig (202.8194.11)
- File Watchers (202.8194.11)
- Grazie (202.8194.11)
- HTTP Client (202.8194.11)
- IntelliLang (202.8194.11)
- Machine Learning Code Completion (202.8194.11)
- Task Management (202.8194.11)
- Terminal (202.8194.11)
- UML (202.8194.11)

**Comment by spont4e** [comment]
Now I updated to PHPStorm 2020.3 and the problem continues, plugins are the same only the GitToolBox version  is (203.3.1)

**Comment by alanhamlett** [comment]
For anyone else wanting to add their list of extensions, to help us find the one causing the issue, here's how to get a list of your installed extensions:

```
Open the settings, go to plugins, filter them by "Enabled", then select the entire list (CTRL+A).
```

From https://stackoverflow.com/a/52036735/1290627

**Comment by spont4e** [comment]
@alanhamlett  Update:
The problems appear only on my Linux Mint 19.3 machine.
I haven't any problems with Wakatime on my Windows 10 machine with the same stack of plugins.

**Custom installed plugins (/downloaded /enabled):**
- .env files support (2020.3)
- Ansible (0.92)
- Bootstrap 3 (4.1.1)
- Case conversion (0.7.1)
- Emmet Everywhere (1.2.5)
- GitToolBox (203.3.1)
- Laravel (0.15.4)
- Translation (3.0)
- WakaTime (11.0.1)
- YAML/Ansible support (0.11.2)

_All other plugins comes by default with PHPStorm_

Today I'll test to disable the latest installed plugins (Ansible and YAML/Ansible support)

**Comment by Vadorequest** [comment]
Got the email too.

First time I get this, and haven't installed a new plugin recently, but what I did yesterday is I opened the same project using 2 different WebStorm windows. And I worked with 3 windows (project A, project B, project A+B monorepo-style), to compare files between A and B easily using the WebStorm "diff" feature (cmd+d). This is most likely why I got this, and not likely to be related to an extension, IMHO.

**Plugins:**

.env files support (2020.3)
ANSI Highlighter (1.2.4)
CodeTogether (3.1.0-00694)
CSV Plugin (2.14.3)
Ideolog (202.0.25.0)
JS GraphQL (2.7.0)
WakaTime (11.0.1)
Docker (203.5981.135)
FTP/SFTP Connectivity (ex. Remote Hosts Access) (203.5981.135)
Vagrant (203.5981.135)
HTML Tools (203.5981.135)
Live Edit (203.5981.135)
Refactor-X (203.5981.135)
XPathView + XSLT (203.5981.135)
IDE Settings Sync (203.5981.135)
Settings Repository (203.5981.135)
Angular and AngularJS (203.5981.135)
CoffeeScript (203.5981.135)
Cordova (203.5981.135)
Cucumber.js (203.5981.135)
JavaScript Debugger (203.5981.135)
JavaScript Intention Power Pack (203.5981.135)
Karma (203.5981.135)
Meteor (203.5981.135)
Node.js (203.5981.135)
Node.js Remote Interpreter (203.5981.135)
Polymer & Web Components (203.5981.135)
Prettier (203.5981.135)
Spy-js (203.5981.135)
TSLint (203.5981.135)
Vue.js (203.5981.135)
Gherkin (203.5981.135)
Markdown (203.5981.135)
Shell Script (203.5981.135)
YAML (203.5981.135)
CSS (203.5981.135)
Less (203.5981.135)
Sass (203.5981.135)
Stylus (203.5981.135)
Tailwind CSS (203.5981.135)
W3C Validators (203.5981.135)
EJS (203.5981.135)
Haml (203.5981.135)
Handlebars/Mustache (203.5981.135)
Java Server Pages (JSP) (203.5981.135)
Pug (ex-Jade) (203.5981.135)
macOS Light Theme (203.5981.135)
ChangeReminder (203.5981.135)
Git (203.5981.135)
GitHub (203.5981.135)
Mercurial (203.5981.135)
Subversion (203.5981.135)
Copyright (203.5981.135)
EditorConfig (203.5981.135)
File Watchers (203.5981.135)
Grazie (203.5981.135)
HTTP Client (203.5981.135)
IDE Features Trainer (203.5981.135)
IntelliLang (203.5981.135)
Machine Learning Code Completion (203.5981.135)
Performance Testing (203.5981.135)
Shared Indexes (203.5981.135)
Styled Components & Styled JSX (203.5981.135)
Task Management (203.5981.135)
Terminal (203.5981.135)
TextMate Bundles (203.5981.135)
Time Tracking (203.5981.135)
UML (203.5981.135)
WebP Support (203.5981.135)

**Comment by spont4e** [comment]
@Vadorequest Can you explain what the operating system is?

**Comment by Vadorequest** [comment]
MacOS Catalina 10.15.4

**Comment by puzzle9** [comment]
I also received the same letter, I guess, maybe because I didn’t close the browser

**Comment by spont4e** [comment]
@alanhamlett I think, the issue was solved when I disable "Synchronize IDE Settings with composer.json" in Settings > Language & Frameworks > PHP > Composer

![Synchronize IDE Settings with composer.json](https://user-images.githubusercontent.com/10523455/108320634-baba3f80-71cb-11eb-8562-192cfa502d45.png)

**Comment by dimer47** [comment]
Hello 👋🏻

Same for me.
My list of plugins used in my IDEs (PHPStorm/WebStorm):
```
com.github.patou.gitmoji
String Manipulation
com.intellij.plugin.adernov.powershell
com.wakatime.intellij.plugin
ru.adelf.idea.dotenv
com.intellij.ml.llm
com.github.copilot
de.timo_reymann.intellij-mjml-support
com.github.masahirosuzuka.PhoneGapIntelliJPlugin
com.nekofar.milad.intellij.nuxtjs
mobi.hsz.idea.gitignore
com.jetbrains.space
de.espend.idea.php.annotation
dev.ekvedaras.laravelquery
fr.adrienbrault.idea.symfony2plugin
com.dmarcotte.handlebars
com.laravel_idea.plugin
```

I hope this can help improve Wakatime support.

Good day

**Comment by cpoissonnier** [comment]
IntelliJ

```
AceJump (3.8.19)
CSV Editor (4.0.2)
Custom Postfix Templates (2.21.0.242)
Eclipse Dark Theme Color Scheme (1.5)
GitHub (243.21565.204-ultimate)
GitHub Copilot (1.5.32-242)
Grazie Pro (0.3.359)
Ideolog (243.21565.208)
Live Edit (243.21565.129)
Monocai Color Theme (2.0.2c)
nginx Support (0.1.9)
Open in GitHub (1.0.6)
PHP (243.21565.211)
Scala (2024.3.20)
String Manipulation (9.15.0)
WakaTime (15.0.3)
Gradle (243.21565.193)
Gradle Extension (243.21565.193)
Maven (243.21565.193)
Maven Extension (243.21565.193)
Code Coverage for Java (243.21565.193)
Database Tools and SQL (243.21565.193)
Flyway (243.21565.193)
Liquibase (243.21565.193)
Reverse Engineering (243.21565.193)
Remote Execution Agent (243.21565.193)
HTML Tools (243.21565.193)
Refactor-X (243.21565.193)
XPathView + XSLT (243.21565.193)
Chinese (Simplified) Language Pack / 中文语言包 (243.21565.193)
Japanese Language Pack / 日本語言語パック (243.21565.193)
Korean Language Pack / 한국어 언어 팩 (243.21565.193)
Backup and Sync (243.21565.193)
Angular (243.21565.193)
JavaScript and TypeScript (243.21565.193)
JavaScript Debugger (243.21565.193)
JavaScript Intention Power Pack (243.21565.193)
Karma (243.21565.193)
Next.js (243.21565.193)
Node.js (243.21565.193)
Polymer & Web Components (243.21565.193)
Prettier (243.21565.193)
React (243.21565.193)
Styled Components & Styled JSX (243.21565.193)
Stylelint (243.21565.193)
TSLint (243.21565.193)
Vite (243.21565.193)
Vue.js (243.21565.193)
Webpack (243.21565.193)
AOP Pointcut Language (243.21565.193)
Jakarta EE Platform (243.21565.193)
Jakarta EE: Bean Validation (243.21565.193)
Jakarta EE: Contexts and Dependency Injection (CDI) (243.21565.193)
Jakarta EE: Data (243.21565.193)
Jakarta EE: Expression Language (EL) (243.21565.193)
Jakarta EE: JPA Model (243.21565.193)
Jakarta EE: Messaging (JMS) (243.21565.193)
Jakarta EE: Persistence (JPA) (243.21565.193)
Jakarta EE: RESTful Web Services (JAX-RS) (243.21565.193)
Jakarta EE: Web/Servlets (243.21565.193)
JVM Microservices Frameworks (243.21565.193)
Lombok (243.21565.193)
Micronaut (243.21565.193)
OpenRewrite (243.21565.193)
Persistence Frameworks (243.21565.193)
Quarkus (243.21565.193)
Reactive Streams (243.21565.193)
Spring (243.21565.193)
Spring Boot (243.21565.193)
Spring Cloud (243.21565.193)
Spring Data (243.21565.193)
Spring Initializr (243.21565.193)
Spring Integration Patterns (243.21565.193)
Spring Messaging (243.21565.193)
Spring Security (243.21565.193)
Spring Web (243.21565.193)
Ktor (243.21565.193)
Groovy (243.21565.193)
Java (243.21565.193)
JSON (243.21565.193)
JSONPath (243.21565.193)
Kotlin (243.21565.193-IJ)
Markdown (243.21565.193)
Properties (243.21565.193)
Shell Script (243.21565.193)
Toml (243.21565.193)
YAML (243.21565.193)
Full Line Code Completion (243.21565.193)
Machine Learning Code Completion (243.21565.193)
Machine Learning in Marketplace (243.21565.193)
Machine Learning in Search Everywhere (243.21565.193)
Turbo Complete (243.21565.193)
Endpoints (243.21565.193)
gRPC (243.21565.193)
HTTP Client (243.21565.193)
OpenAPI Specifications (243.21565.193)
Protocol Buffers (243.21565.193)
Remote Development Gateway (243.21565.193)
CSS (243.21565.193)
Less (243.21565.193)
PostCSS (243.21565.193)
Sass (243.21565.193)
Tailwind CSS (243.21565.193)
Apache Velocity (243.21565.193)
FreeMarker (243.21565.193)
Jakarta EE: Server Pages (JSP) (243.21565.193)
Thymeleaf (243.21565.193)
JUnit (243.21565.193)
TestNG (243.21565.193)
Git (243.21565.193)
Mercurial (243.21565.193)
Perforce Helix Core (243.21565.193)
Subversion (243.21565.193)
Bytecode Viewer (243.21565.193)
Code With Me (243.21565.193)
Copyright (243.21565.193)
Cron Expressions (243.21565.193)
Dependency Structure Matrix (243.21565.193)
Diagrams (243.21565.193)
Eclipse Interoperability (243.21565.193)
EditorConfig (243.21565.193)
Grazie Lite (243.21565.193)
IDE Features Trainer (243.21565.193)
In-Editor Performance Hints (243.21565.193)
IntelliLang (243.21565.193)
Java Bytecode Decompiler (243.21565.193)
Java IDE Customization (243.21565.193)
Java Internationalization (243.21565.193)
Java Stream Debugger (243.21565.193)
Package Checker (243.21565.193)
Performance Testing (243.21565.193)
Qodana (243.21565.193)
Shared Project Indexes (243.21565.193)
Task Management (243.21565.193)
Terminal (243.21565.193)
TextMate Bundles (243.21565.193)
Time Tracking (243.21565.193)
WebP Support (243.21565.193)
```

**Comment by HelgeStenstrom** [comment]
I was asked in an e-mail to provide information, 

> We noticed some unusual coding activity from your Rustrover WakaTime plugin Yesterday:
> You have many duplicate heartbeat events.
> 
> This is usually caused by another Rustrover extension tricking WakaTime into thinking you’re moving the cursor, or editing files.
> If you would like to help fix this, please add the list of Rustrover extensions you have installed to an existing [GitHub issue](https://github.com/wakatime/jetbrains-wakatime/issues?q=%22unusual+coding+activity%22) or just reply to this email.

so here it is:

I have only 4 downloaded and active plugins in RustRover:
.ignore (version 4.5.6, from JetBrains)
GitHub (from JetBrains)
PlantUML Integration (version 7.11.2-IJ2023.2)
WakaTime (version 15.0.3).

That being said, I see problems in the idea.log file, which make me think that the problems with wakatime has nothing to do with conflicting plugins.

From the log file:

> 2025-02-28 21:51:47,233 [ 301181]   WARN - WakaTime - Cannot run program "/Users/helge/.wakatime/wakatime-cli-darwin-amd64": error=13, Permission denied
> java.io.IOException: Cannot run program "/Users/helge/.wakatime/wakatime-cli-darwin-amd64": error=13, Permission denied
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1170)
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
> 	at java.base/java.lang.Runtime.exec(Runtime.java:681)
> 	at java.base/java.lang.Runtime.exec(Runtime.java:530)
> 	at com.wakatime.intellij.plugin.WakaTime.sendHeartbeat(WakaTime.java:318)
> 	at com.wakatime.intellij.plugin.WakaTime.processHeartbeatQueue(WakaTime.java:308)
> 	at com.wakatime.intellij.plugin.WakaTime.access$000(WakaTime.java:53)
> 	at com.wakatime.intellij.plugin.WakaTime$3.run(WakaTime.java:165)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
> 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
> 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)
> Caused by: java.io.IOException: error=13, Permission denied
> 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
> 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:295)
> 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:225)
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1126)
> 	... 13 more


Hope this helps.

**Comment by alanhamlett** [comment]
> my phpstorm version
> 
> * PhpStorm 2025.1.0.1
> * Build #PS-251.23774.466, built on April 23, 2025
> 
> and here's my list...

Maybe one of those plugins is causing continuous file save/edit events to trigger, or I've also seen this happen when using the IDE to tail a logfile by opening the logfile in the editor instead of using tail in the output window.

**Comment by bestgopher** [comment]
I got that email.

```
GoLand 2025.1
Build #GO-251.23774.430, built on April 14, 2025
Source revision: 745c51c81a5c5

You have a perpetual fallback license for this version.
Subscription is active until June 30, 2026.
Runtime version: 21.0.6+9-b895.109 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.5
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 8
Metal Rendering is ON
Registry:
  ide.completion.variant.limit=500
  suggest.all.run.configurations.from.context=FALSE
  ide.experimental.ui=true
  completion.cloud.enableTextCompletion=false
Non-Bundled Plugins:
  com.redhat.devtools.lsp4ij (0.13.0)
  com.wakatime.intellij.plugin (15.0.4)
  com.cppcxy.Intellij-SumnekoLua (3.14.0.45-IDEA243)
  com.jetbrains.space (251.23774.318)
  org.mvnsearch.plugins.justPlugin (0.6.16)
  com.intellij.ml.llm (251.23774.42.28.7.1)
  PlantUML integration (7.11.2-IJ2023.2)
  co.anbora.labs.jenkins.jenkinsFile (1.2.1)
  com.mallowigi (101.2.0)
  izhangzhihao.rainbow.brackets (2024.2.11-241)
  zielu.gittoolbox (600.1.2+243)
```

```
Atom Material Icons (101.2.0)
GitToolBox (600.1.2+243)
Jenkinsfile (1.2.1)
JetBrains AI Assistant (251.23774.42.28.7.1)
Just (0.6.16)
LSP4IJ (0.13.0)
PlantUML Integration (7.11.2-IJ2023.2)
Rainbow Brackets (2024.2.11-241)
Space (251.23774.318)
SumnekoLua (3.14.0.45-IDEA243)
WakaTime (15.0.4)
Database Tools and SQL (251.23774.430)
Docker (251.23774.430)
FTP/SFTP/WebDAV Connectivity (251.23774.430)
Kubernetes (251.23774.430)
Remote Execution Agent (251.23774.430)
SSH Remote Run (251.23774.430)
HTML Tools (251.23774.430)
Refactor-X (251.23774.430)
Chinese (Simplified) Language Pack / 中文语言包 (251.23774.430)
Japanese Language Pack / 日本語言語パック (251.23774.430)
Korean Language Pack / 한국어 언어 팩 (251.23774.430)
Backup and Sync (251.23774.430)
JavaScript and TypeScript (251.23774.430)
JavaScript Debugger (251.23774.430)
JavaScript Intention Power Pack (251.23774.430)
React (251.23774.430)
Stylelint (251.23774.430)
Webpack (251.23774.430)
VSCode Keymap (251.23774.430)
Go (251.23774.430)
JSON (251.23774.430)
JSONPath (251.23774.430)
Makefile Language (251.23774.430)
Markdown (251.23774.430)
Shell Script (251.23774.430)
YAML (251.23774.430)
Full Line Code Completion (251.23774.430)
Machine Learning Code Completion (251.23774.430)
Machine Learning in Search Everywhere (251.23774.430)
Endpoints (251.23774.430)
gRPC (251.23774.430)
HTTP Client (251.23774.430)
OpenAPI Specifications (251.23774.430)
Protocol Buffers (251.23774.430)
Dev Containers (251.23774.430)
Remote Development Gateway (251.23774.430)
CSS (251.23774.430)
Go Template (251.23774.430)
Colorful Darcula Color Scheme (251.23774.430)
GoLand Solarized Color Scheme (251.23774.430)
Monokai Color Scheme (251.23774.430)
Git (251.23774.430)
GitHub (251.23774.430-IU)
GitLab (251.23774.430-IU)
Mercurial (251.23774.430)
Code With Me (251.23774.430)
Configuration Script (251.23774.430)
Copyright (251.23774.430)
Diagrams (251.23774.430)
EditorConfig (251.23774.430)
File Watchers (251.23774.430)
Go Linter (251.23774.430)
Grazie Lite (251.23774.430)
IDE Features Trainer (251.23774.430)
IntelliLang (251.23774.430)
Package Checker (251.23774.430)
Performance Testing (251.23774.430)
Qodana (251.23774.430)
Shared Project Indexes (251.23774.430)
Terminal (251.23774.430)
TextMate Bundles (251.23774.430)
```

**Comment by collinskoech11** [comment]
got that email 

```
code --list-extensions --show-versions
anseki.vscode-color@0.4.5
antiantisepticeye.vscode-color-picker@0.0.4
apollographql.vscode-apollo@2.6.2
burkeholland.simple-react-snippets@1.2.8
dsznajder.es7-react-js-snippets@4.4.3
eamodio.gitlens@17.3.4
esbenp.prettier-vscode@11.0.0
github.copilot@1.350.0
github.copilot-chat@0.27.3
henoc.color-scheme-selector@0.2.0
mquandalle.graphql@0.1.2
ms-python.debugpy@2025.10.0
ms-python.python@2025.12.0
ms-python.vscode-pylance@2025.6.2
ms-python.vscode-python-envs@1.2.0
naumovs.color-highlight@2.8.0
rangav.vscode-thunder-client@2.37.5
ritwickdey.liveserver@5.7.9
simonsiefke.svg-preview@2.8.3
solomonkinard.git-blame@0.2.74
vue.volar@3.0.5
waderyan.gitblame@11.1.4
wakatime.vscode-wakatime@25.3.0
```
