### ISSUE TITLE
Start failed on Android Studio 

### ISSUE THREAD

**Issue by mal7othify** [wakatime/jetbrains-wakatime#160]
Since I updated Android Studio to the latest version **(Arctic Fox 2020.3.1 Canary 5)** I have been getting the following error message once I start AS and I cannot bypass it until I disable WakaTime plugin. 

```
"Start Failed"
Internal error. Please refer to https://code.google.com/p/android/issues

java.lang.LinkageError: loader constraint violation for class com.android.tools.idea.ServerFlagList: when selecting overriding method 'com.google.protobuf.MessageLite com.android.tools.idea.ServerFlagList.getDefaultInstanceForType()' the class loader com.intellij.ide.plugins.cl.PluginClassLoader @55e78300 of the selected method's type com.android.tools.idea.ServerFlagList, and the class loader com.intellij.ide.BootstrapClassLoaderUtil$TransformingLoader @101df177 for its super type com.google.protobuf.MessageLiteOrBuilder have different Class objects for the type com.google.protobuf.MessageLite used in the signature (com.android.tools.idea.ServerFlagList is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @55e78300, parent loader 'bootstrap'; com.google.protobuf.MessageLiteOrBuilder is in unnamed module of loader com.intellij.ide.BootstrapClassLoaderUtil$TransformingLoader @101df177, parent loader 'platform')
    at com.android.tools.idea.serverflags.ServerFlagUtilitiesKt.unmarshalFlagList(ServerFlagUtilities.kt:41)
    at com.android.tools.idea.serverflags.ServerFlagDownloader$Companion.downloadServerFlagList(ServerFlagDownloader.kt:56)
    at com.android.tools.idea.serverflags.ServerFlagDownloader$Companion.downloadServerFlagList(ServerFlagDownloader.kt:36)
    at com.android.tools.idea.serverflags.ServerFlagDownloader.downloadServerFlagList(ServerFlagDownloader.kt)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    at java.base/java.lang.Thread.run(Thread.java:834)

-----
Your JRE: 11.0.8+10-b944.6842174 x86_64 (N/A)
/Users/mar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7101492/Android Studio Preview.app/Contents/jre/jdk/Contents/Home
```

**Comment by mal7othify** [comment]
This issue has been solved
