### ISSUE TITLE
Wakatime freezes the whole IDEA

### ISSUE THREAD

**Issue by imkiva** [wakatime/jetbrains-wakatime#170]
<details>
<summary>IDEA version</summary>

```
IntelliJ IDEA 2021.1 Beta (Ultimate Edition)
Build #IU-211.6556.6, built on March 17, 2021
IntelliJ IDEA EAP User
Expiration date: April 16, 2021
Runtime version: 11.0.10+9-b1341.20 aarch64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.2.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: run.processes.with.pty=false
Non-Bundled Plugins: com.wakatime.intellij.plugin (12.0.4), org.antlr.intellij.plugin (1.16)
Kotlin: 211-1.4.21-release-IJ6556.4
```

</details>

<details>
<summary>Stack trace</summary>

```
Freeze in EDT for 70 seconds
IDE KILLED! Sampled time: 61600ms, sampling rate: 100ms, GC time: 0ms (0%), Class loading: 0%, load average: 1.39

com.intellij.diagnostic.Freeze
	at java.base@11.0.10/java.lang.Object.wait(Native Method)
	at java.base@11.0.10/java.lang.Object.wait(Object.java:328)
	at java.base@11.0.10/java.lang.ProcessImpl.waitFor(ProcessImpl.java:495)
	at com.wakatime.intellij.plugin.WakaTime$6.run(WakaTime.java:437)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.ApplicationImpl$$Lambda$396/0x0000000800509440.run(Unknown Source)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop@11.0.10/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop@11.0.10/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop@11.0.10/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop@11.0.10/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base@11.0.10/java.security.AccessController.doPrivileged(Native Method)
	at java.base@11.0.10/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop@11.0.10/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.ide.IdeEventQueue$$Lambda$522/0x0000000800687840.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.ide.IdeEventQueue$$Lambda$515/0x0000000800681040.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop@11.0.10/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop@11.0.10/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop@11.0.10/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop@11.0.10/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop@11.0.10/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop@11.0.10/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

</details>

**Comment by alanhamlett** [comment]
Let's leave it open unless it's fixed?

**Comment by imkiva** [comment]
After upgrading to 12.0.7 this problem never happened again. So I believe this should be fixed.
