### ISSUE TITLE
not work 2021.1 wakatime version 12.0.7

### ISSUE THREAD

**Issue by RazgrizHsu** [wakatime/jetbrains-wakatime#172]
![image](https://user-images.githubusercontent.com/3889141/116851497-03a75f00-ac25-11eb-9d2c-af41a55af6f6.png)

logs
```
java.lang.IllegalArgumentException: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
	at org.apache.xerces.jaxp.DocumentBuilderFactoryImpl.setAttribute(Unknown Source)
	at com.github.markusbernhardt.proxy.util.PListParser.parse(PListParser.java:274)
	at com.github.markusbernhardt.proxy.util.PListParser.load(PListParser.java:302)
	at com.github.markusbernhardt.proxy.search.desktop.osx.OsxProxySearchStrategy.getProxySelector(OsxProxySearchStrategy.java:92)
	at com.github.markusbernhardt.proxy.search.desktop.DesktopProxySearchStrategy.getProxySelector(DesktopProxySearchStrategy.java:38)
	at com.github.markusbernhardt.proxy.ProxySearch.getProxySelector(ProxySearch.java:222)
	at com.intellij.util.net.IdeaWideProxySelector.selectUsingPac(IdeaWideProxySelector.java:85)
	at com.intellij.util.net.IdeaWideProxySelector.select(IdeaWideProxySelector.java:63)
	at com.intellij.util.proxy.CommonProxy.select(CommonProxy.java:213)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at com.wakatime.intellij.plugin.Dependencies.downloadFile(Dependencies.java:187)
	at com.wakatime.intellij.plugin.Dependencies.installCLI(Dependencies.java:138)
	at com.wakatime.intellij.plugin.WakaTime$1.run(WakaTime.java:113)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by RazgrizHsu** [comment]
update 12.0.8 resolved
