### ISSUE TITLE
2021.2 EAP: exception on startup

### ISSUE THREAD

**Issue by pahan35** [wakatime/jetbrains-wakatime#179]
> java.lang.Throwable: Attempt to load key 'ide.new.project.model.cache' for not yet loaded registry. Use system properties instead of registry values to configure behaviour at early startup stages.
> 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
> 	at com.intellij.openapi.util.registry.RegistryValue._get(RegistryValue.java:216)
> 	at com.intellij.openapi.util.registry.RegistryValue.get(RegistryValue.java:194)
> 	at com.intellij.openapi.util.registry.RegistryValue.asBoolean(RegistryValue.java:63)
> 	at com.intellij.openapi.util.registry.Registry.is(Registry.java:57)
> 	at com.intellij.workspaceModel.ide.impl.WorkspaceModelCacheImpl.<init>(WorkspaceModelCacheImpl.kt:40)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
> 	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:52)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:881)
> 	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:48)
> 	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:36)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:590)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:573)
> 	at com.intellij.openapi.project.impl.DefaultProject.getService(DefaultProject.java:215)
> 	at com.intellij.workspaceModel.ide.WorkspaceModelCache$Companion.getInstance(WorkspaceModelCache.kt:24)
> 	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl.<init>(WorkspaceModelImpl.kt:43)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
> 	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:52)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:881)
> 	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:48)
> 	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:36)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:590)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:573)
> 	at com.intellij.openapi.project.impl.DefaultProject.getService(DefaultProject.java:215)
> 	at com.intellij.workspaceModel.ide.WorkspaceModel$Companion.getInstance(WorkspaceModel.kt:79)
> 	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModuleManagerComponentBridge.<init>(ModuleManagerComponentBridge.kt:328)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
> 	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:52)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:881)
> 	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:35)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:407)
> 	at com.intellij.openapi.project.impl.DefaultProjectImpl.init(DefaultProject.java:317)
> 	at com.intellij.openapi.project.impl.DefaultProject$1.init(DefaultProject.java:54)
> 	at com.intellij.openapi.project.impl.DefaultProjectTimed.get(DefaultProjectTimed.java:33)
> 	at com.intellij.openapi.project.impl.DefaultProject.getDelegate(DefaultProject.java:137)
> 	at com.intellij.openapi.project.impl.DefaultProject.getMessageBus(DefaultProject.java:245)
> 	at com.intellij.openapi.project.impl.ProjectManagerImpl.getDefaultProject(ProjectManagerImpl.java:207)
> 	at com.wakatime.intellij.plugin.WakaTime$2.run(WakaTime.java:130)
> 	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
> 	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
> 	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
> 	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
> 	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
> 	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
> 	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
> 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:881)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:750)
> 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:437)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
> 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:436)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:482)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by gandarez** [comment]
Hi @pahan35,

Which WakaTime version you have installed?

**Comment by alexresiga** [comment]
@gandarez from the Non-Bundled Plugins list at the end: com.wakatime.intellij.plugin (13.0.2)

**Comment by alexresiga** [comment]
@gandarez Hi! Still happens using com.wakatime.intellij.plugin (13.1.0) and IntelliJ IDEA 2021.3 EAP (Ultimate Edition) Build #IU-213.4293, built on September 28, 2021
