### ISSUE TITLE
/.wakatime/wakatime-cli-darwin-arm64": error=2, No such file or directory

### ISSUE THREAD

**Issue by shmueldabomb441** [wakatime/jetbrains-wakatime#198]
I installed WakaTime on my new 2020 M1 mac, and got the following stacktrace:

```
WakaTime - Cannot run program "/Users/shmuel/.wakatime/wakatime-cli-darwin-arm64": error=2, No such file or directory 
java.io.IOException: Cannot run program "/Users/shmuel/.wakatime/wakatime-cli-darwin-arm64": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:592)
	at java.base/java.lang.Runtime.exec(Runtime.java:451)
	at com.wakatime.intellij.plugin.WakaTime.sendHeartbeat(WakaTime.java:256)
	at com.wakatime.intellij.plugin.WakaTime.processHeartbeatQueue(WakaTime.java:249)
	at com.wakatime.intellij.plugin.WakaTime.access$100(WakaTime.java:47)
	at com.wakatime.intellij.plugin.WakaTime$4.run(WakaTime.java:166)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 13 more

```
This is the directory contents  of /shmuel/ on my fresh mac:
AndroidStudioProjects
Desktop
Documents
Downloads
Movies
Music
Pictures
Public

**Comment by alanhamlett** [comment]
It's not detecting your ARM processor correctly and trying to use the Intel version of the wakatime-cli binary. Here's the method that detects arm/amd:

https://github.com/wakatime/jetbrains-wakatime/blob/9e9b6982c0fe095e7a1b910b57571ae35ca3130c/src/com/wakatime/intellij/plugin/Dependencies.java#L462

It's inputs are `System.getProperty("os.arch")` and `System.getProperty("os.name")`. Can you find the value of those two system properties within the context of your IDE's Java?

**Comment by gandarez** [comment]
https://stackoverflow.com/questions/66410522/value-of-system-getpropertyos-arch-on-m1-mac

**Comment by anmol098** [comment]
https://github.com/wakatime/wakatime-cli/releases/tag/v1.35.4

Download the darwin-arm64 zip 
unzip that to /Users/<user-name>/.wakatime/

this will resolve the issue.

**Comment by shmueldabomb441** [comment]
I don't have that folder... Sometimes the plugin works and sometimes it doesn't!

**Comment by alanhamlett** [comment]
It might not be displaying that folder because it starts with a dot. Does this show it?

`ls -la /Users/shmuel`

**Comment by LunaYJ** [comment]
> https://github.com/wakatime/wakatime-cli/releases/tag/v1.35.4
> 
> Download the darwin-arm64 zip unzip that to /Users//.wakatime/
> 
> this will resolve the issue.

Hi,
I tried your solution, but it's not work.

after I unzip the file to $HOME/.wakatime/

after several seconds, or minutes, the file will disappear.

My mac system is macOS Monterey  12.2.1

**Comment by LunaYJ** [comment]
> Please add this line to your `~/.wakatime.cfg` file: `debug = true`
> 
> Then restart your IDE and share your `idea.log` file contents: https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

Hi 
thanks for reply

I have opened `debug` mode

and here is the log message
```
2022-04-01 21:29:58,544 [  32673]  DEBUG -                       WakaTime - Executing CLI: [/Users/lunazhou/.wakatime/wakatime-cli-darwin-amd64, --entity, /Users/lunazhou/Project/MY/ghost.local/content/themes/Luno/partials/comments.hbs, --time, 1648819789.9370, --key, XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXd799, --project, Luno, --alternate-language, Handlebars/Mustache, --plugin, WebStorm/2021.3.3 WebStorm-wakatime/13.1.14] 
2022-04-01 21:29:58,544 [  32673]  DEBUG -                       WakaTime - Api Key: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXd799 
2022-04-01 21:29:58,548 [  32677]   WARN -                       WakaTime - Cannot run program "/Users/lunazhou/.wakatime/wakatime-cli-darwin-amd64": error=2, No such file or directory 
java.io.IOException: Cannot run program "/Users/lunazhou/.wakatime/wakatime-cli-darwin-amd64": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:592)
	at java.base/java.lang.Runtime.exec(Runtime.java:451)
	at com.wakatime.intellij.plugin.WakaTime.sendHeartbeat(WakaTime.java:264)
	at com.wakatime.intellij.plugin.WakaTime.processHeartbeatQueue(WakaTime.java:257)
	at com.wakatime.intellij.plugin.WakaTime.access$100(WakaTime.java:47)
	at com.wakatime.intellij.plugin.WakaTime$4.run(WakaTime.java:172)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 13 more
```

**Comment by gandarez** [comment]
Is that still NOK @LunaYJ?
