### ISSUE TITLE
Assertion failed: assert !app.isDispatchThread()

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/jetbrains-wakatime#202]
Rubymine: Build #RM-213.5744.194, built on November 24, 2021
WakaTime: version 13.1.11

```
java.lang.Throwable: Assertion failed: assert !app.isDispatchThread()
at com.intellij.openapi.diagnostic.Logger.assertTrue(http://Logger.java:218)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(http://ActionManagerImpl.java:140)
at com.jetbrains.rdserver.ui.actionPopupMenu.BackendActionManager.<init>(BackendActionManager.kt:16)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(http://NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(…http://DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(http://Constructor.java:490)
at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:876)
at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:37)
at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:595)
at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:569)
at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
at com.intellij.openapi.actionSystem.ActionManager.getInstance(http://ActionManager.java:30)
at com.intellij.openapi.actionSystem.DefaultActionGroup.addAction(http://DefaultActionGroup.java:163)
at com.intellij.openapi.actionSystem.DefaultActionGroup.add(http://DefaultActionGroup.java:134)
at com.intellij.ui.mac.touchbar.Touchbar.setButtonActions(http://Touchbar.java:58)
at com.intellij.ui.mac.touchbar.Touchbar.setButtonActions(http://Touchbar.java:49)
at com.intellij.openapi.ui.DialogWrapper.createSouthPanel(http://DialogWrapper.java:564)
at com.intellij.openapi.ui.DialogWrapper.init(http://DialogWrapper.java:1340)
at com.wakatime.intellij.plugin.ApiKey.<init>(http://ApiKey.java:31)
at com.wakatime.intellij.plugin.WakaTime$2.run(http://WakaTime.java:136)
at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(http://TransactionGuardImpl.java:214)
at com.intellij.openapi.application.TransactionGuardImpl.access$200(http://TransactionGuardImpl.java:21)
at com.intellij.openapi.application.TransactionGuardImpl$2.run(http://TransactionGuardImpl.java:196)
at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(http://ApplicationImpl.java:805)
at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(http://ApplicationImpl.java:348)
at com.intellij.openapi.application.impl.FlushQueue.doRun(http://FlushQueue.java:82)
at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(http://FlushQueue.java:131)
at com.intellij.openapi.application.impl.FlushQueue.flushNow(http://FlushQueue.java:47)
at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(http://FlushQueue.java:187)
at java.desktop/java.awt.event.InvocationEvent.dispatch(http://InvocationEvent.java:313)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(http://EventQueue.java:776)
at java.desktop/java.awt.EventQueue$4.run(http://EventQueue.java:727)
at java.desktop/java.awt.EventQueue$4.run(http://EventQueue.java:721)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(http://ProtectionDomain.java:85)
at java.desktop/java.awt.EventQueue.dispatchEvent(http://EventQueue.java:746)
at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(http://IdeEventQueue.java:891)
at com.intellij.ide.IdeEventQueue._dispatchEvent(http://IdeEventQueue.java:760)
at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(http://IdeEventQueue.java:447)
at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(http://CoreProgressManager.java:818)
at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(http://IdeEventQueue.java:446)
at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(http://ApplicationImpl.java:805)
at com.intellij.ide.IdeEventQueue.dispatchEvent(http://IdeEventQueue.java:492)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(http://EventDispatchThread.java:203)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(http://EventDispatchThread.java:124)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(http://EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(http://EventDispatchThread.java:109)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(http://EventDispatchThread.java:101)
at java.desktop/java.awt.EventDispatchThread.run(http://EventDispatchThread.java:90)
```

**Comment by alanhamlett** [comment]
Looks like #200, which should have been fixed in v13.1.11.
