### ISSUE TITLE
Wakatime not work at 14.1.4 version 

### ISSUE THREAD

**Issue by HealUP** [wakatime/jetbrains-wakatime#247]
**background**:

> **this is my first time to install wakatime and i correctly input the Secret API Key**     i sure

**phenomenon**:😭

 it stopped working , If i enable debug mode i get the following exception:

```
java.io.IOException: Cannot run program "C:\Users\86159\.wakatime\wakatime-cli-windows-amd64.exe": CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:592)
	at java.base/java.lang.Runtime.exec(Runtime.java:451)
	at com.wakatime.intellij.plugin.WakaTime.sendHeartbeat(WakaTime.java:305)
	at com.wakatime.intellij.plugin.WakaTime.processHeartbeatQueue(WakaTime.java:298)
	at com.wakatime.intellij.plugin.WakaTime.access$000(WakaTime.java:52)
	at com.wakatime.intellij.plugin.WakaTime$3.run(WakaTime.java:159)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:487)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 13 more
```

how to solve? help me 😭😭 thanks 

I have uninstalled and installed several times but it didnt work. Is there anyway to add wakatime-cli.exe manually?

**Comment by alanhamlett** [comment]
What are the contents of your `C:\Users\86159\.wakatime\` folder?

**Comment by HealUP** [comment]
谢谢！邮件已收到，祝您万事顺遂，平安喜乐！

**Comment by alanhamlett** [comment]
> Is there anyway to add wakatime-cli.exe manually?

To manually install wakatime-cli, the same as the plugin tries to do, download the [latest release](https://github.com/wakatime/wakatime-cli/releases), then extract the zip to `C:\Users\86159\.wakatime\` and symlink or copy `wakatime-cli-windows-amd64.exe` to `C:\Users\86159\.wakatime\wakatime-cli.exe`.

**Comment by HealUP** [comment]
> 
the folder include wakatime-cli0ktgx.zip, but it's empty and i try to unzip the compressed file, it show:The file is a compressed file and cannot be opened.

**Comment by HealUP** [comment]
> > Is there anyway to add wakatime-cli.exe manually?
> 
> To manually install wakatime-cli, the same as the plugin tries to do, download the [latest release](https://github.com/wakatime/wakatime-cli/releases), then extract the zip to `C:\Users\86159\.wakatime\` and symlink or copy `wakatime-cli-windows-amd64.exe` to `C:\Users\86159\.wakatime\wakatime-cli.exe`.

it works,
thanks for yout help,sincerly☺️

**Comment by alanhamlett** [comment]
That sounds like the plugin wasn't able to connect to GitHub due to a networking issue, so it couldn't download wakatime-cli. Now it should work but you won't get updates to wakatime-cli if a new version is released, not that big of a deal.

**Comment by HealUP** [comment]
> 
i get it, if necessary,i will manually install wakatime-cli when a new version is released, thanks again

**Comment by HealUP** [comment]
> That sounds like the plugin wasn't able to connect to GitHub due to a networking issue, so it couldn't download wakatime-cli. Now it should work but you won't get updates to wakatime-cli if a new version is released, not that big of a deal.

i get it, if necessary,i will manually install wakatime-cli when a new version is released, thanks again
