### ISSUE TITLE
Error WebStorm 9

### ISSUE THREAD

**Issue by extensionsapp** [wakatime/jetbrains-wakatime#25]
```
Plugin 'com.wakatime.intellij.plugin' failed to initialize and will be disabled.  Please restart WebStorm.

com.intellij.diagnostic.PluginException: com/wakatime/intellij/plugin/WakaTime : Unsupported major.minor version 52.0 [Plugin: com.wakatime.intellij.plugin]
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:270)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:426)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:416)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.access$000(ComponentManagerImpl.java:402)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:107)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:86)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:110)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:511)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:493)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:158)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:66)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:364)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.lang.UnsupportedClassVersionError: com/wakatime/intellij/plugin/WakaTime : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:213)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:209)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:185)
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
    ... 30 more
```

**Comment by dleffler** [comment]
Also in 8.03

**Comment by alanhamlett** [comment]
I'm able to reproduce this, but haven't figured out what is causing this error yet.

**Comment by alanhamlett** [comment]
Compiling the release with IntelliJ 14 is causing this error for an unknown reason. I've released a new version compiled with IntelliJ 13 which works.

Please re-enable or re-install the WakaTime plugin, then restart your IDE.

**Comment by alanhamlett** [comment]
Turns out IntelliJ 14 is using the JRE 1.8 SDK but I only had 1.6 JRE on my machine, which is why it worked when compiled with IntelliJ 13.

**Comment by dleffler** [comment]
As a note, if you're using PHPStorm v8.0.x, you'll need to uninstall the broken version and reinstall the older version since the recompiled update doesn't apply to PHPStorm v8.0.x.

**Comment by sklirg** [comment]
I noticed this problem as well. 
I'm running on a Macbook Air, OS X Yosemite.

The problem is that IntelliJ uses the OS X JRE by default, which is JRE 1.6.

The fix for me was to make IntelliJ run using the 1.8 JRE, which you can specify in `/Applications/IntelliJ IDEA 14.app/Contents/Info.plist`, where `IntelliJ IDEA 14.app` is the version/suite of IDEA application.

Search for they key/value pair 
```
<key>JVMVersion</key>
<string>1.6*</string>
```
And change it to 
```
<key>JVMVersion</key>
<string>1.8*</string>
```

This will make your IDEA start using JRE 1.8.

Source: [Selecting the JDK version the IDE will run under](https://intellij-support.jetbrains.com/entries/23455956-Selecting-the-JDK-version-the-IDE-will-run-under)
