### ISSUE TITLE
IDE Internal Errors 1 of 1 Exception in plugin WakaTime (14.1.4). Disable plugin

### ISSUE THREAD

**Issue by Guellaf** [wakatime/jetbrains-wakatime#255]
PS
IDE Internal Errors
1 of 1 Exception in plugin WakaTime (14.1.4). Disable plugin... This plugin is not a production of JetBrains. Please report the problem to Waka Time.
----------------------------------------------------------------------------------------------------------------------------------------------
PhpStorm 2023.1
Build #PS-231.8109.199, built on March 29, 2023
Licensed to Abd Elhalim Guellaf
Subscription is active until March 7, 2024.
Runtime version: 17.0.6+10-b829.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1516M
Cores: 6
Registry:
    debugger.new.tool.window.layout=true
    run.processes.with.pty=TRUE
    ide.experimental.ui=true

Non-Bundled Plugins:
    Batch Scripts Support (1.0.13)
    com.myoutdesk.tailwind_formatter (2.0.7)
    com.github.copilot (1.2.5.2507)
    com.intellij.ideolog (203.0.30.0)
    com.markskelton.one-dark-theme (5.7.4)
    CMD Support (1.0.5)
    com.wakatime.intellij.plugin (14.1.4)
    com.intellij.grazie.pro (0.3.215)
    ru.adelf.idea.dotenv (2023.1)
    nl.deschepers.laraveltinker (2.6.0)
    de.espend.idea.php.annotation (9.2.1)
    de.beyondco.tinkerwell.tinkerwell (2.5.0)
    net.rentalhost.plugins.laravel.hammer (0.2.1)
    com.pestphp.pest-intellij (1.9.2)
    com.laravel_idea.tailwind (1.4.1)
    dev.ekvedaras.laravelquery (4.0.2)
    fr.adrienbrault.idea.symfony2plugin (2022.1.246)
    com.dmarcotte.handlebars (231.8109.91)
    com.github.inxilpro.intellijalpine (v0.4.2)
----------------------------------------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/47402966/233867232-620b4163-fad4-4eda-b202-203b21c610f6.png)

**Comment by caijinyc** [comment]
I have the same problem in WebStorm.
<img width="699" alt="image" src="https://github.com/wakatime/jetbrains-wakatime/assets/32707518/c760e7b9-b43f-4f9f-885b-f860c5592297">

**Comment by alanhamlett** [comment]
It's working for me in PHPStorm and WebStorm on Mac. Can you find the error traceback from your `idea.log` file?

**Comment by xeladsn** [comment]
Facing the same issue while using PyCharm 2023.1.2 Professional Edition on Windows 11
Quite disturbing as every time I'm launching my IDE the plugin crashes with an IDE Internal Error, with this message below:

_java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.wm.StatusBar.updateWidget(String)" because "this.widget.statusBar" is null
	at com.wakatime.intellij.plugin.CustomStatusBar$WakaTimeStatusBarWidget$StatusBarPresenter.getPopupStep(CustomStatusBar.java:98)
	at com.intellij.openapi.wm.StatusBarWidget$MultipleTextValuesPresentation.getPopup(StatusBarWidget.kt:70)
	at com.intellij.openapi.wm.impl.status.MultipleTextValues$2.onClick(IdeStatusBarImpl.kt:868)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:58)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6656)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at java.desktop/java.awt.Component.processEvent(Component.java:6421)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2804)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:790)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:763)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:761)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:615)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)_

**Comment by alanhamlett** [comment]
@xeladsn that was just fixed a few minutes ago with #257.

**Comment by Guellaf** [comment]
✅ Error fixed in my side after updating PhpStorm & Wakatime plugin
