### ISSUE TITLE
WakaTime is stuck on inititialized and doesn't display time

### ISSUE THREAD

**Issue by consolexyz** [wakatime/jetbrains-wakatime#263]

**Comment by alanhamlett** [comment]
After turning on debug mode, do you see any errors in your `idea.log` file?

**Comment by sunist-c** [comment]
I have the same problem, but when I turned on debug mode, cleared `idea.log` and restarted JetBrains IDEA, it stuck on `0 secs` and have no changes all the time.

OS: macOS 14
SOC: Apple M2 Pro
IDE: Goland 2023.2.2
Wakatime Version: 14.2.1

----

Content of `idea.log`:

Initialize:

```log
2023-10-07 10:42:17,150 [    287]   INFO - WakaTime - Initializing WakaTime plugin v14.2.1 (https://wakatime.com/)
2023-10-07 10:42:17,151 [    288]   FINE - WakaTime - Logging level set to DEBUG
No changes: {String Manipulation=PluginData(enabled=true, category=PLUGINS, dependencies=[com.intellij.modules.platform]), com.aiwan.gorm=PluginData(enabled=false, category=PLUGINS, dependencies=[org.jetbrains.plugins.go, com.intellij.modules.goland, com.intellij.modules.lang, com.intellij.modules.platform, com.intellij.database, com.aiwan.request-tool, org.jetbrains.plugins.yaml]), com.chesterccw.excelreader=PluginData(enabled=true, category=PLUGINS, dependencies=[com.intellij.modules.platform]), com.codigrate.aurora-borealis.theme=PluginData(enabled=true, category=UI, dependencies=[com.intellij.modules.platform]), com.github.copilot=PluginData(enabled=true, category=PLUGINS, dependencies=[com.intellij.modules.platform, com.intellij.modules.lang]), com.intellij.tasks=PluginData(enabled=true, category=PLUGINS, dependencies=[com.intellij.modules.xml]), com.mallowigi=PluginData(enabled=true, category=PLUGINS, dependencies=[com.intellij.modules.platform]), com.markskelton.one-dark-theme=PluginData(enabled=true, category=PLUGINS, dependencies=[com.intellij.modules.platform]), com.nasller.CodeGlancePro=PluginData(enabled=true, category=PLUGINS, dependencies=[com.intellij.modules.lang]), com.wakatime.intellij.plugin=PluginData(enabled=true, category=PLUGINS, dependencies=[com.intellij.modules.lang, com.intellij.modules.platform]), com.ypwang.plugin.go-linter=PluginData(enabled=true, category=PLUGINS, dependencies=[com.intellij.modules.lang, org.jetbrains.plugins.go]), izhangzhihao.rainbow.brackets=PluginData(enabled=true, category=PLUGINS, dependencies=[com.intellij.modules.lang]), org.intellij.plugins.postcss=PluginData(enabled=true, category=PLUGINS, dependencies=[]), org.jetbrains.plugins.vue=PluginData(enabled=true, category=PLUGINS, dependencies=[]), zielu.gittoolbox=PluginData(enabled=true, category=PLUGINS, dependencies=[com.intellij.modules.platform, Git4Idea])}
2023-10-07 10:42:18,845 [   1982]   FINE - WakaTime - wakatime-cli local version output: "v1.85.1"
2023-10-07 10:42:18,846 [   1983]   FINE - WakaTime - wakatime-cli local version exit code: 0
2023-10-07 10:42:18,846 [   1983]   FINE - WakaTime - getUrlAsString(https://api.github.com/repos/wakatime/wakatime-cli/releases/latest)
2023-10-07 10:42:19,210 [   2347]   FINE - WakaTime - Using cached wakatime-cli version from config: v1.85.1
2023-10-07 10:42:19,210 [   2347]   FINE - WakaTime - Latest wakatime-cli version: v1.85.1
2023-10-07 10:42:19,210 [   2347]   INFO - WakaTime - wakatime-cli is up to date.
2023-10-07 10:42:19,210 [   2347]   FINE - WakaTime - wakatime-cli location: /Users/sunist/.wakatime/wakatime-cli-darwin-arm64
2023-10-07 10:42:20,441 [   3578]   FINE - WakaTime - Executing CLI: [/Users/sunist/.wakatime/wakatime-cli-darwin-arm64, --today, --key, XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXbe2c]
2023-10-07 10:42:23,110 [   6247]   FINE - WakaTime - Command finished with return value: 0
2023-10-07 10:42:47,161 [  30298]   FINE - WakaTime - Executing CLI: [/Users/sunist/.wakatime/wakatime-cli-darwin-arm64, --plugin, GoLand/2023.2.2 GoLand-wakatime/14.2.1, --entity, /Users/sunist/Projects/GitHub/ceobebot-qqchanel/processor/interface.go, --time, 1696646540.4410, --key, XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXbe2c, --lines-in-file, 11, --alternate-project, ceobebot-qqchanel, --alternate-language, Go, --extra-heartbeats]
```

Working for a while:

```log
2023-10-07 10:57:59,121 [ 942258]   FINE - WakaTime - Executing CLI: [/Users/sunist/.wakatime/wakatime-cli-darwin-arm64, --today, --key, XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXbe2c]
2023-10-07 10:58:01,595 [ 944732]   FINE - WakaTime - Command finished with return value: 0
2023-10-07 10:58:17,163 [ 960300]   FINE - WakaTime - Executing CLI: [/Users/sunist/.wakatime/wakatime-cli-darwin-arm64, --plugin, GoLand/2023.2.2 GoLand-wakatime/14.2.1, --entity, /Users/sunist/Projects/GitHub/ceobebot-qqchanel/processor/handler.go, --time, 1696647479.1230, --key, XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXbe2c, --lines-in-file, 61, --alternate-project, ceobebot-qqchanel, --alternate-language, Go]
2023-10-07 10:58:20,194 [ 963331]   FINE - WakaTime - Command finished with return value: 0

2023-10-07 11:00:11,462 [1074599]   FINE - WakaTime - Executing CLI: [/Users/sunist/.wakatime/wakatime-cli-darwin-arm64, --today, --key, XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXbe2c]
2023-10-07 11:00:14,363 [1077500]   FINE - WakaTime - Command finished with return value: 0
2023-10-07 11:00:17,088 [1080225]   FINE - WakaTime - Executing CLI: [/Users/sunist/.wakatime/wakatime-cli-darwin-arm64, --plugin, GoLand/2023.2.2 GoLand-wakatime/14.2.1, --entity, /Users/sunist/Projects/GitHub/ceobebot-qqchanel/processor/handler.go, --time, 1696647611.4650, --key, XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXbe2c, --lines-in-file, 61, --alternate-project, ceobebot-qqchanel, --alternate-language, Go]

2023-10-07 11:00:19,679 [1082816]   FINE - WakaTime - Command finished with return value: 0
```

**Comment by sunist-c** [comment]
Additional information, other JetBrains IDE(s) also have the same problem, this is `idea.log` of JetBrains DataGrip, I do nothing and it stuck on inititialized and doesn't display time.

```log
2023-09-27 07:15:45,695 [    712]   INFO - WakaTime - Finished downloading and installing wakatime-cli.
2023-09-27 07:15:48,090 [   3107]   WARN - WakaTime - Cannot run program "/Users/sunist/.wakatime/wakatime-cli-darwin-arm64": error=2, No such file or directory
java.io.IOException: Cannot run program "/Users/sunist/.wakatime/wakatime-cli-darwin-arm64": error=2, No such file or directory
	at com.wakatime.intellij.plugin.WakaTime$8.run(WakaTime.java:670)
2023-09-27 07:49:55,387 [2050404]   WARN - WakaTime - Cannot run program "/Users/sunist/.wakatime/wakatime-cli-darwin-arm64": error=2, No such file or directory
java.io.IOException: Cannot run program "/Users/sunist/.wakatime/wakatime-cli-darwin-arm64": error=2, No such file or directory
	at com.wakatime.intellij.plugin.WakaTime.sendHeartbeat(WakaTime.java:308)
	at com.wakatime.intellij.plugin.WakaTime.processHeartbeatQueue(WakaTime.java:298)
	at com.wakatime.intellij.plugin.WakaTime.access$000(WakaTime.java:52)
	at com.wakatime.intellij.plugin.WakaTime$3.run(WakaTime.java:159)
2023-10-05 15:28:52,781 [720787798]   WARN - WakaTime - Cannot run program "/Users/sunist/.wakatime/wakatime-cli-darwin-arm64": error=2, No such file or directory
java.io.IOException: Cannot run program "/Users/sunist/.wakatime/wakatime-cli-darwin-arm64": error=2, No such file or directory
	at com.wakatime.intellij.plugin.WakaTime$8.run(WakaTime.java:670)
2023-10-05 15:29:26,537 [720821554]   WARN - WakaTime - Cannot run program "/Users/sunist/.wakatime/wakatime-cli-darwin-arm64": error=2, No such file or directory
java.io.IOException: Cannot run program "/Users/sunist/.wakatime/wakatime-cli-darwin-arm64": error=2, No such file or directory
	at com.wakatime.intellij.plugin.WakaTime.sendHeartbeat(WakaTime.java:308)
	at com.wakatime.intellij.plugin.WakaTime.processHeartbeatQueue(WakaTime.java:298)
	at com.wakatime.intellij.plugin.WakaTime.access$000(WakaTime.java:52)
	at com.wakatime.intellij.plugin.WakaTime$3.run(WakaTime.java:159)
2023-10-05 15:46:05,710 [721820727]   WARN - WakaTime - Cannot run program "/Users/sunist/.wakatime/wakatime-cli-darwin-arm64": error=2, No such file or directory
java.io.IOException: Cannot run program "/Users/sunist/.wakatime/wakatime-cli-darwin-arm64": error=2, No such file or directory
	at com.wakatime.intellij.plugin.WakaTime$8.run(WakaTime.java:670)
2023-10-05 15:47:05,743 [721880760]   WARN - WakaTime - Cannot run program "/Users/sunist/.wakatime/wakatime-cli-darwin-arm64": error=2, No such file or directory
java.io.IOException: Cannot run program "/Users/sunist/.wakatime/wakatime-cli-darwin-arm64": error=2, No such file or directory
	at com.wakatime.intellij.plugin.WakaTime$8.run(WakaTime.java:670)
```

**Comment by gandarez** [comment]
The log says wakatime-cli is not found on your machine. Would you mind uninstalling and installing again WakaTime from any of Jetbrains IDEs and see if it works?

```
WARN - WakaTime - Cannot run program "/Users/sunist/.wakatime/wakatime-cli-darwin-arm64": error=2, No such file or directory
java.io.IOException: Cannot run program "/Users/sunist/.wakatime/wakatime-cli-darwin-arm64": error=2, No such file or directory
	at com.wakatime.intellij.plugin.WakaTime$8.run(WakaTime.java:670)
```

**Comment by xuyanshi** [comment]
I have the same problem!

**Comment by alanhamlett** [comment]
@xuyanshi does the file `~/.wakatime/wakatime-cli-darwin-arm64` exist and is it runnable?

**Comment by xuyanshi** [comment]
> @xuyanshi does the file `~/.wakatime/wakatime-cli-darwin-arm64` exist and is it runnable?
> 
> Also, what error messages do you see in your `idea.log` file when turning on debug mode?

Thanks for your reply!

Firstly, "wakatime-cli-windows-amd64.exe" exists but is not runnable.

![image](https://github.com/wakatime/jetbrains-wakatime/assets/36392244/9b747fb5-629a-4306-b5d6-a9eb0353bb27)

OS:
```
Edition	Windows 11 Pro
Version	23H2
OS build	22631.2428
```

Processor:	Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz

IDE:
```
IntelliJ IDEA 2023.2.4 (Ultimate Edition)

Runtime version: 17.0.8.1+7-b1000.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
```

Wakatime: com.wakatime.intellij.plugin (14.2.3)

---

And here are error messages related to Wakatime in my `idea.log`.
```
2023-11-02 12:20:40,337 [    828]   INFO - WakaTime - Initializing WakaTime plugin v14.2.3 (https://wakatime.com/)
2023-11-02 12:20:40,349 [    840]   FINE - WakaTime - Logging level set to DEBUG
2023-11-02 12:20:40,366 [    857]   WARN - WakaTime - Cannot run program "C:\Users\xuyanshi\.wakatime\wakatime-cli-windows-amd64.exe": CreateProcess error=193, %1 is not a valid Win32 application
java.io.IOException: Cannot run program "C:\Users\xuyanshi\.wakatime\wakatime-cli-windows-amd64.exe": CreateProcess error=193, %1 is not a valid Win32 application
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at java.base/java.lang.Runtime.exec(Runtime.java:594)
	at java.base/java.lang.Runtime.exec(Runtime.java:453)
	at com.wakatime.intellij.plugin.Dependencies.isCLIOld(Dependencies.java:99)
	at com.wakatime.intellij.plugin.WakaTime$1.run(WakaTime.java:109)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:499)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 15 more

2023-11-02 12:20:40,366 [    857]   INFO - WakaTime - Upgrading wakatime-cli ...
2023-11-02 12:20:40,367 [    858]   FINE - WakaTime - getUrlAsString(https://api.github.com/repos/wakatime/wakatime-cli/releases/latest)
```

**Comment by alanhamlett** [comment]
Nothing logged after `2023-11-02 12:20:40,367 [    858]   FINE - WakaTime - getUrlAsString`? It should have then logged a success or failure showing if `wakatime-cli` was downloaded or not.

**Comment by alanhamlett** [comment]
@xuyanshi please try updating to the new plugin version released today v14.3.0.

**Comment by xuyanshi** [comment]
> @xuyanshi please try updating to the new plugin version released today v14.3.0.

Sorry for bothering you again.

I have updated it and even reinstalled it. However, it's still useless.

The file "wakatime-cli-windows-amd64.exe" exists but is not runnable. By the way, when I tried to unzip "waketime-cli.zip" manually, I was notified by Bandizip that this archive file was broken.

Here are all the messages in `idea.log` including "Waka":
```
2023-11-02 17:49:45,573 [    898]   INFO - WakaTime - Initializing WakaTime plugin v14.3.0 (https://wakatime.com/)
2023-11-02 17:49:45,588 [    913]   FINE - WakaTime - Logging level set to DEBUG
2023-11-02 17:49:45,606 [    931]   WARN - WakaTime - Cannot run program "C:\Users\xuyanshi\.wakatime\wakatime-cli-windows-amd64.exe": CreateProcess error=193, %1 is not a valid Win32 application
java.io.IOException: Cannot run program "C:\Users\xuyanshi\.wakatime\wakatime-cli-windows-amd64.exe": CreateProcess error=193, %1 is not a valid Win32 application
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at java.base/java.lang.Runtime.exec(Runtime.java:594)
	at java.base/java.lang.Runtime.exec(Runtime.java:453)
	at com.wakatime.intellij.plugin.Dependencies.isCLIOld(Dependencies.java:100)
	at com.wakatime.intellij.plugin.WakaTime$1.run(WakaTime.java:109)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:499)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 15 more

2023-11-02 17:49:45,607 [    932]   INFO - WakaTime - Upgrading wakatime-cli ...
2023-11-02 17:49:45,608 [    933]   FINE - WakaTime - DownloadFile(https://github.com/wakatime/wakatime-cli/releases/latest/download/wakatime-cli-windows-amd64.zip)
2023-11-02 17:49:45,644 [    969]   INFO - #c.i.o.v.n.p.PersistentFSConnector - VFS uses strict names enumerator
2023-11-02 17:49:45,703 [   1028]   INFO - #c.i.o.v.n.p.PersistentFSConnector - VFS uses new (streamlined) attributes storage
2023-11-02 17:49:45,871 [   1196]   INFO - #c.i.u.n.s.CertificateManager - Default SSL context initialized
2023-11-02 17:49:45,873 [   1198]   INFO - #c.i.o.a.i.ActionManagerImpl - keymap "Eclipse" not found PluginDescriptor(name=IDEA CORE, id=com.intellij, descriptorPath=plugin.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 2022.3.2\lib, version=232.10203.10, package=com.intellij.structuralsearch, isBundled=true)

(...)

2023-11-02 17:50:07,474 [  22799]   WARN - WakaTime - Connection timed out: connect
java.net.ConnectException: Connection timed out: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at com.wakatime.intellij.plugin.Dependencies.downloadFile(Dependencies.java:272)
	at com.wakatime.intellij.plugin.Dependencies.installCLI(Dependencies.java:187)
	at com.wakatime.intellij.plugin.WakaTime$1.run(WakaTime.java:117)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-11-02 17:50:07,476 [  22801]   INFO - WakaTime - Finished upgrading wakatime-cli.
2023-11-02 17:50:07,478 [  22803]   FINE - WakaTime - wakatime-cli location: C:\Users\xuyanshi\.wakatime\wakatime-cli-windows-amd64.exe
2023-11-02 17:50:15,651 [  30976]   FINE - WakaTime - Executing CLI: [C:\Users\xuyanshi\.wakatime\wakatime-cli-windows-amd64.exe, --plugin, IDEA/2023.2.4 IDEA-wakatime/14.3.0, --entity, C:/Users/xuyanshi/Code/IdeaProjects/LeetCode/src/LeetCode.java, --time, 1698918589.2450, --key, XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX949b, --lines-in-file, 64, --alternate-project, LeetCode, --alternate-language, JAVA]
2023-11-02 17:50:15,652 [  30977]   WARN - WakaTime - Cannot run program "C:\Users\xuyanshi\.wakatime\wakatime-cli-windows-amd64.exe": CreateProcess error=193, %1 is not a valid Win32 application
java.io.IOException: Cannot run program "C:\Users\xuyanshi\.wakatime\wakatime-cli-windows-amd64.exe": CreateProcess error=193, %1 is not a valid Win32 application
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at java.base/java.lang.Runtime.exec(Runtime.java:594)
	at java.base/java.lang.Runtime.exec(Runtime.java:453)
	at com.wakatime.intellij.plugin.WakaTime.sendHeartbeat(WakaTime.java:308)
	at com.wakatime.intellij.plugin.WakaTime.processHeartbeatQueue(WakaTime.java:298)
	at com.wakatime.intellij.plugin.WakaTime.access$000(WakaTime.java:52)
	at com.wakatime.intellij.plugin.WakaTime$3.run(WakaTime.java:159)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:499)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 13 more

2023-11-02 17:50:18,492 [  33817]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities to files
```

**Comment by alanhamlett** [comment]
The error message when downloading `wakatime-cli` from GitHub is:

`WARN - WakaTime - Connection timed out: connect`

Do you have a proxy set in your `~/.wakatime.cfg` file?

**Comment by xuyanshi** [comment]
> The error message when downloading `wakatime-cli` from GitHub is:
> 
> `WARN - WakaTime - Connection timed out: connect`
> 
> Do you have a proxy set in your `~/.wakatime.cfg` file?

No, proxy is equals to empty in `~/.wakatime.cfg`.

**Comment by alanhamlett** [comment]
Ok, I'm not sure why the plugin can't connect to GitHub. Try manually downloading and extracting this zip into `~/.wakatime/` folder:
https://github.com/wakatime/wakatime-cli/releases/latest/download/wakatime-cli-windows-amd64.zip

**Comment by xuyanshi** [comment]
I'm sorry, but it still does not work.

Strangely, the Wakatime plugin works normally in VSCode but does not work in all JetBrains' IDEs on my PC.

**Comment by alanhamlett** [comment]
Does your Jetbrains IDE have a proxy set? That's the most likely reason it would work in VS Code but not in Jetbrains on the same machine. Check for the proxy in your IDE settings and remove it if there's one:
![image](https://github.com/wakatime/jetbrains-wakatime/assets/522344/2272631b-8706-45d6-8ad2-2efcfe9de70f)

**Comment by xuyanshi** [comment]
> Does your Jetbrains IDE have a proxy set? That's the most likely reason it would work in VS Code but not in Jetbrains on the same machine. Check for the proxy in your IDE settings and remove it if there's one: ![image](https://user-images.githubusercontent.com/522344/280237011-2272631b-8706-45d6-8ad2-2efcfe9de70f.png)

Thanks, this problem has been solved. 

Dramatically, the solution is quite the opposite. When I used a VPN to connect to Wakatime, it worked.
 
By the way, I have to use a proxy because a large number of websites such as GitHub and Google are blocked or polluted in China, maybe Wakatime is on this unlucky list.
