### ISSUE TITLE
Wakatime 14.3.11 not work on IDEA 2023.3.6

### ISSUE THREAD

**Issue by counter2015** [wakatime/jetbrains-wakatime#278]
After update wakatime to 14.3.11, it cant show icon on idea tool bar and collect data.
And then I try to downgrade it to the former version 14.1.4, it works.

Suspicious logs `idea.log`

```
2024-03-23 22:27:42,955 [   6653]   WARN - #c.i.i.c.t.p.v.p.StateDatabaseParser - No suitable driver found for jdbc:sqlite:C:/Users/***/AppData/Roaming/Code/User/globalStorage/state.vscdb
java.sql.SQLException: No suitable driver found for jdbc:sqlite:C:/Users/***/AppData/Roaming/Code/User/globalStorage/state.vscdb
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:706)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:252)
	at com.intellij.ide.customize.transferSettings.providers.vscode.parsers.StateDatabaseParser.process(StateDatabaseParser.kt:27)
	at com.intellij.ide.customize.transferSettings.providers.vscode.VSCodeSettingsProcessor.getProcessedSettings(VSCodeSettingsProcessor.kt:54)
	at com.intellij.ide.customize.transferSettings.providers.vscode.VSCodeTransferSettingsProvider$cachedIdeVersion$2.invoke(VSCodeTransferSettingsProvider.kt:25)
	at com.intellij.ide.customize.transferSettings.providers.vscode.VSCodeTransferSettingsProvider$cachedIdeVersion$2.invoke(VSCodeTransferSettingsProvider.kt:24)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.intellij.ide.customize.transferSettings.providers.vscode.VSCodeTransferSettingsProvider.getCachedIdeVersion(VSCodeTransferSettingsProvider.kt:24)
	at com.intellij.ide.customize.transferSettings.providers.vscode.VSCodeTransferSettingsProvider.getIdeVersion(VSCodeTransferSettingsProvider.kt:30)
	at com.intellij.ide.customize.transferSettings.providers.vscode.VSCodeTransferSettingsProvider.getIdeVersions(VSCodeTransferSettingsProvider.kt:20)
	at com.intellij.ide.customize.transferSettings.providers.vscode.VSCodeTransferSettingsProvider.getIdeVersions(VSCodeTransferSettingsProvider.kt:12)
	at com.intellij.ide.customize.transferSettings.TransferSettingsDataProviderSession$createBaseIdeVersions$1.invoke(TransferSettingsDataProvider.kt:57)
	at com.intellij.ide.customize.transferSettings.TransferSettingsDataProviderSession$createBaseIdeVersions$1.invoke(TransferSettingsDataProvider.kt:50)
	at com.intellij.ide.customize.transferSettings.TransferSettingsDataProviderSession.createBaseIdeVersions$lambda$0(TransferSettingsDataProvider.kt:50)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4853)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4861)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.intellij.ide.customize.transferSettings.TransferSettingsDataProviderSession.createBaseIdeVersions(TransferSettingsDataProvider.kt:65)
	at com.intellij.ide.customize.transferSettings.TransferSettingsDataProviderSession.access$createBaseIdeVersions(TransferSettingsDataProvider.kt:42)
	at com.intellij.ide.customize.transferSettings.TransferSettingsDataProviderSession$baseIdeVersions$2.invoke(TransferSettingsDataProvider.kt:46)
	at com.intellij.ide.customize.transferSettings.TransferSettingsDataProviderSession$baseIdeVersions$2.invoke(TransferSettingsDataProvider.kt:46)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.intellij.ide.customize.transferSettings.TransferSettingsDataProviderSession.getBaseIdeVersions(TransferSettingsDataProvider.kt:46)
	at com.intellij.ide.customize.transferSettings.TransferSettingsDataProvider.refresh(TransferSettingsDataProvider.kt:30)
	at com.intellij.ide.customize.transferSettings.TransferSettingsDataProvider.<init>(TransferSettingsDataProvider.kt:22)
	at com.intellij.ide.customize.transferSettings.TransferSettingsDataProvider.<init>(TransferSettingsDataProvider.kt:19)
	at com.intellij.ide.customize.transferSettings.TransferSettingsProjectActivity.<init>(TransferSettingsProjectActivity.kt:16)
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:962)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:954)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.instantiateClass(XmlExtensionAdapter.kt:78)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter$SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.kt:89)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:49)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.kt:30)
	at com.intellij.openapi.extensions.ExtensionPointNameKt.createOrError(ExtensionPointName.kt:290)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:589)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:72)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2.invokeSuspend(StartupManagerImpl.kt:181)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```

**Comment by alanhamlett** [comment]
It works for me on Mac. It's possible there was a problem when upgrading, but re-installing (by downgrading) fixed it. Can you try upgrading again and see if it's working?

**Comment by counter2015** [comment]
After re-upgrading, it also does work for me on Win11 .
I turned on debug mode, nothing special found in `wakatime.log`
```
{"caller":"cmd/run.go:99","func":"cmd.Run","level":"debug","message":"command: version","now":"2024-03-24T11:16:21+08:00","os/arch":"windows/amd64","version":"v1.90.0"}
```

This is my config, it works fine on older version.
```
[settings]
api_key = waka_a7a00372-fb2f-****-****-afced465ca6e
proxy = http://127.0.0.1:1080
debug = false
status_bar_enabled = true
no_ssl_verify = true
```

**Comment by alanhamlett** [comment]
I've seen in rare cases randomly the install is corrupted, and re-installing always fixes it. Looks like that was the case here.
