### ISSUE TITLE
Exception in plugin WakaTime (15.0.1) on PHPStorm 2024.2

### ISSUE THREAD

**Issue by 7-zete-7** [wakatime/jetbrains-wakatime#293]
stacktrace.txt
```
java.lang.Throwable: Do not use, call '#setLevel(LogLevel)' instead
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.openapi.diagnostic.Logger.setLevel(Logger.java:484)
	at com.wakatime.intellij.plugin.WakaTime.setLoggingLevel(WakaTime.java:594)
	at com.wakatime.intellij.plugin.WakaTime.initComponent(WakaTime.java:98)
	at com.intellij.serviceContainer.ComponentInstanceInitializer.createInstance$suspendImpl(ComponentInstanceInitializer.kt:27)
	at com.intellij.serviceContainer.ComponentInstanceInitializer.createInstance(ComponentInstanceInitializer.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invokeSuspend(LazyInstanceHolder.kt:162)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invokeSuspend(LazyInstanceHolder.kt:160)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:27)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:90)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.initialize(LazyInstanceHolder.kt:145)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.access$initialize(LazyInstanceHolder.kt:13)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.tryInitialize(LazyInstanceHolder.kt:135)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt:95)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstanceInCallerContext$suspendImpl(LazyInstanceHolder.kt:87)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstanceInCallerContext(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.UtilKt.preloadAllInstances(util.kt:47)
	at com.intellij.serviceContainer.ComponentManagerImpl$createInitOldComponentsTask$1.invokeSuspend(ComponentManagerImpl.kt:478)
	at com.intellij.serviceContainer.ComponentManagerImpl$createInitOldComponentsTask$1.invoke(ComponentManagerImpl.kt)
	at com.intellij.serviceContainer.ComponentManagerImpl$createInitOldComponentsTask$1.invoke(ComponentManagerImpl.kt)
	at com.intellij.platform.ide.bootstrap.AppServicePreloadingKt$postAppRegistered$3$1.invokeSuspend(appServicePreloading.kt:140)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:320)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

IDE info
```
PhpStorm 2024.2
Build #PS-242.20224.361, built on August 10, 2024
Licensed to Stanislau Kviatkouski
Subscription is active until August 4, 2025.
Runtime version: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4052M
Cores: 16
Registry:
  debugger.new.tool.window.layout=true
  vcs.log.index.enable=true
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
  ide.images.show.chessboard=true
  eslint.additional.file.extensions=svelte
Non-Bundled Plugins:
  com.intellij.datagen (242.20224.159)
  cc.allape.caddyfile (0.2.1)
  net.sjrx.intellij.plugins.systemdunitfiles (223.240807.213)
  de.femtopedia.diffplugin (2.1.14)
  lermitage.intellij.extratci (2024.3.1)
  com.github.kikimanjaro.intellify (0.0.7)
  MultiHighlight (3.2.0)
  org.intellij.plugins.hcl (242.20224.159)
  org.toml.lang (242.20224.155)
  com.nasller.CodeGlancePro (1.8.7)
  idea.plugin.protoeditor (242.20224.155)
  com.ultrahob.zerolength.plugin (0.95)
  io.aesy.regex101 (0.2)
  org.jetbrains.settingsRepository (242.20224.155)
  Keymap exporter (2.6)
  org.jetbrains.plugins.go-template (242.20224.155)
  String Manipulation (9.14.1)
  dev.meanmail.plugin.nginx-intellij-plugin (2024.3)
  com.wakatime.intellij.plugin (15.0.1)
  com.intellij.mermaid (0.0.22+IJ.232)
  com.intellij.grpc (242.20224.361)
  com.intellij.kubernetes (242.20224.175)
  PlantUML integration (7.10.1-IJ2023.2)
  com.github.siropkin.kursor (1.3.0)
  com.dsoftware.ghtoolbar (2024.2.6)
  com.jetbrains.changeReminder (242.20224.155)
  com.intellij.queryComplexity (242.20224.159)
  com.intellij.bigdatatools.core (242.20224.300)
  com.intellij.bigdatatools.binary.files (242.20224.159)
  com.intellij.bigdatatools.rfs (242.20224.300)
  com.intellij.lang.jsgraphql (242.20224.155)
  dev.blachut.svelte.lang (242.20224.155)
  com.dmarcotte.handlebars (242.20224.159)
  mdx.js (242.20224.159)
  deno (242.20224.155)
  mobi.hsz.idea.gitignore (4.5.3)
  com.intellij.wiremock (242.20224.155)
  com.intellij.microservices.ui (242.20224.175)
  com.intellij.plugins.html.instantEditing (242.20224.155)
  com.jetbrains.plugins.jade (242.20224.159)
  izhangzhihao.rainbow.brackets (2024.2.6-241)
  lv.midiana.misc.phpstorm-plugins.deep-keys (2022.08.03.001)
  cn.yiiguxing.plugin.translate (3.6.4)
  ru.adelf.idea.dotenv (2024.2)
  com.ramusthastudio.plugin.unixtimestamp (6.3.0)
  de.espend.idea.php.toolbox (6.2.0)
  de.espend.idea.php.annotation (11.0.1)
  fr.adrienbrault.idea.symfony2plugin (2024.1.275)
  zielu.gittoolbox (500.2.14+242)
  de.espend.idea.php.phpunit (7.1)
```

**Comment by 7-zete-7** [comment]
Duplicate of https://github.com/wakatime/jetbrains-wakatime/issues/283
