### ISSUE TITLE
Permission denied??? wakatime stopped working 3 days ago

### ISSUE THREAD

**Issue by yolowex** [wakatime/jetbrains-wakatime#298]
error at my `idea.log` in Intellij.

```
2024-09-13 02:42:11,876 [ 900277]   WARN - WakaTime - Cannot run program "/home/pickle/.wakatime/wakatime-cli-linux-amd64": error=13, Permission denied
java.io.IOException: Cannot run program "/home/pickle/.wakatime/wakatime-cli-linux-amd64": error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at java.base/java.lang.Runtime.exec(Runtime.java:594)
	at java.base/java.lang.Runtime.exec(Runtime.java:453)
	at com.wakatime.intellij.plugin.WakaTime.sendHeartbeat(WakaTime.java:318)
	at com.wakatime.intellij.plugin.WakaTime.processHeartbeatQueue(WakaTime.java:308)
	at com.wakatime.intellij.plugin.WakaTime.access$000(WakaTime.java:53)
	at com.wakatime.intellij.plugin.WakaTime$3.run(WakaTime.java:165)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
	
I don't recall changing its permission. it stopped working 3 days ago. it worked fine just before that, i didn't update my Intellij neither I updated wakatime plugin nor I messed with its folder.
	
also, when i try to run that bin in question, it throws a seg fault.

	
```
	└─$ ./wakatime-cli-linux-amd64
zsh: segmentation fault  ./wakatime-cli-linux-amd64
```

here are the permissions of the scripts:
```
└─$ lash
total 4.1M
4.0K drwxrwxr-x  2 pickle pickle 4.0K Sep 10 22:59 .
4.0K drwx------ 46 pickle pickle 4.0K Sep 13 11:29 ..
2.8M -rw-------  1 pickle pickle 4.0M Sep 10 15:56 offline_heartbeats.bdb
   0 lrwxrwxrwx  1 pickle pickle   47 Aug 12 18:56 wakatime-cli -> /home/pickle/.wakatime/wakatime-cli-linux-amd64
944K -rwxrwxr-x  1 pickle pickle 944K Sep 10 22:59 wakatime-cli-linux-amd64
424K -rw-rw-r--  1 pickle pickle 421K Sep 10 22:59 wakatime-cli.zip
4.0K -rw-rw-r--  1 pickle pickle  282 Sep 10 15:56 wakatime-internal.cfg
 12K -rw-------  1 pickle pickle  10K Sep  9 17:23 wakatime.log
```

should I give it 777 permission? (seems a bit dangerous tbh)

**Comment by alanhamlett** [comment]
It just needs execute permission, so `chmod a+x wakatime-cli-linux-amd64`. The IDE plugin should have done that when downloading wakatime-cli, but you can do it manually.
