### ISSUE TITLE
Heartbeat is broken in PhpStorm

### ISSUE THREAD

**Issue by MadMind** [wakatime/jetbrains-wakatime#32]
Fresh install of the plugin (never used it before) throws the following errors:

2015-05-17 00:21:46,376 [ 118953]  DEBUG -                       WakaTime - Executing CLI: [pythonw, C:/xxx/.WebIde80/config/plugins/WakaTime-resources\wakatime-master\wakatime\cli.py, --key, XXX-XXX-XXX, --file, D:/Dev/xxx/index.html.twig, --project, XXX, --plugin, PhpStorm/8.0.3 PhpStorm-wakatime/4.0.7, --write] 
2015-05-17 00:21:47,355 [ 119932]  DEBUG -                       WakaTime - Traceback (most recent call last): 
2015-05-17 00:21:47,355 [ 119932]  DEBUG -                       WakaTime -   File "C:/xxx/.WebIde80/config/plugins/WakaTime-resources\wakatime-master\wakatime\cli.py", line 18, in <module> 
2015-05-17 00:21:47,355 [ 119932]  DEBUG -                       WakaTime -     sys.exit(wakatime.main(sys.argv)) 
2015-05-17 00:21:47,355 [ 119932]  DEBUG -                       WakaTime -   File "C:\xxx\.WebIde80\config\plugins\WakaTime-resources\wakatime-master\wakatime\base.py", line 461, in main 
2015-05-17 00:21:47,355 [ 119932]  DEBUG -                       WakaTime -     **vars(args) 
2015-05-17 00:21:47,355 [ 119932]  DEBUG -                       WakaTime - TypeError: send_heartbeat() got multiple values for keyword argument 'project' 
2015-05-17 00:21:47,355 [ 119932]  DEBUG -                       WakaTime - Command finished with return value: 1

**Comment by alanhamlett** [comment]
Fixed with v4.0.8 of the plugin. Thanks for the traceback!
