### ISSUE TITLE
Crashing Android Studio

### ISSUE THREAD

**Issue by bausmeier** [wakatime/jetbrains-wakatime#34]
Hi

I just updated the WakaTime plugin in Android Studio to v4.0.9 and now it seems to be causing it to crash. From the error message it seems like this might be related to https://github.com/wakatime/jetbrains-wakatime/commit/946d8c5d59587ccce9b2026e2e22b17094e05024. I have added the stack trace below.

In the event log I see:

```
9:17:57 AM Throwable
           Access is allowed from event dispatch thread only.
           Details: EventQueue.isDispatchThread()=false
           isDispatchThread()=false
           Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@3694e499
           Current thread: Thread[ApplicationImpl pooled thread 9,4,main] 1292489900
           SystemEventQueueThread: Thread[AWT-EventQueue-0 1.2#AI-141.1903250, eap:false,6,main] 1461139405
           "AWT-EventQueue-0 1.2#AI-141.1903250, eap:false" prio=0 tid=0x0 nid=0x0 runnable
           java.lang.Thread.State: RUNNABLE
           at com.intellij.ui.tabs.impl.JBTabsImpl.doLayout(JBTabsImpl.java:1498)
           at java.awt.Container.validateTree(Container.java:1688)
           at java.awt.Container.validateTree(Container.java:1697)
           at java.awt.Container.validateTree(Container.java:1697)
           at java.awt.Container.validateTree(Container.java:1697)
           at java.awt.Container.validateTree(Container.java:1697)
           at java.awt.Container.validateTree(Container.java:1697)
           at java.awt.Container.validateTree(Container.java:1697)
           at java.awt.Container.validateTree(Container.java:16...
```

And in the console I see:

```
----------- 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1036)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1026)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1018)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.assertDispatchThread(FocusManagerImpl.java:1195)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.invalidateFocusRequestsQueue(FocusManagerImpl.java:693)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.isFocusTransferReady(FocusManagerImpl.java:684)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.isFocusBeingTransferred(FocusManagerImpl.java:1148)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.isFocusBeingTransferred(IdeFocusManagerImpl.java:144)
	at com.intellij.ide.impl.DataManagerImpl.getFocusedComponent(DataManagerImpl.java:248)
	at com.intellij.ide.impl.DataManagerImpl.getDataContext(DataManagerImpl.java:202)
	at com.wakatime.intellij.plugin.WakaTime.getProjectName(WakaTime.java:216)
	at com.wakatime.intellij.plugin.WakaTime.executeCLI(WakaTime.java:173)
	at com.wakatime.intellij.plugin.WakaTime$3$1.run(WakaTime.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:878)
	at com.wakatime.intellij.plugin.WakaTime$3.run(WakaTime.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
[ 164908]  ERROR - plication.impl.ApplicationImpl - Android Studio 1.2.1.1  Build #AI-141.1903250 
[ 164908]  ERROR - plication.impl.ApplicationImpl - JDK: 1.7.0_79 
[ 164908]  ERROR - plication.impl.ApplicationImpl - VM: OpenJDK 64-Bit Server VM 
[ 164908]  ERROR - plication.impl.ApplicationImpl - Vendor: Oracle Corporation 
[ 164908]  ERROR - plication.impl.ApplicationImpl - OS: Linux 
```

**Comment by yjchieng** [comment]
Same issue happens in RubyMine. (I say same because the stack trace is almost similar.)
The IDE hanged forever, after I start editing some source file.

Have to force close and disable plugin for now.

p/s: I updated the plugin to latest version today.

**Comment by toptalo** [comment]
In PhpStorm too.

**Comment by alanhamlett** [comment]
Sorry about that, should be fixed now with 4b58e5b69e6617161f26019c631bc6736ede92cb.

**Comment by toptalo** [comment]
Yes it helps. Thanks!

**Comment by DavidFrahm** [comment]
How do I install the latest code, i.e. master?  In my prefs I only see released versions.

**Comment by alanhamlett** [comment]
Uninstall, then re-install the plugin to get this update since the version number is the same.

**Comment by DavidFrahm** [comment]
@alanhamlett Why not just bump the version? Don't you want people who already have the current version to get the fix?

(and I'm really asking; thought there might be something I could learn here)

**Comment by alanhamlett** [comment]
@DavidFrahm you're right, users shouldn't have to reinstall. I've bumped the version to 4.0.10.
