### ISSUE TITLE
crash on first install on Ubuntu 14.10 in Android Studio 

### ISSUE THREAD

**Issue by intari** [wakatime/jetbrains-wakatime#38]
after I install WakaTime plugin in Android Studio on next restart I get
[  31871]   WARN - inspections.IntellijLintClient - Incorrect detector reported disabled issue UselessParent 
[  31872]   WARN - inspections.IntellijLintClient - Incorrect detector reported disabled issue UselessParent 
[  31875]   WARN - inspections.IntellijLintClient - Incorrect detector reported disabled issue UselessParent 
[  31879]   WARN - inspections.IntellijLintClient - Incorrect detector reported disabled issue UselessParent 
[  31883]   WARN - inspections.IntellijLintClient - Incorrect detector reported disabled issue UselessParent 
[  33218]   WARN - inspections.IntellijLintClient - Incorrect detector reported disabled issue UselessParent 
[  33219]   WARN - inspections.IntellijLintClient - Incorrect detector reported disabled issue UselessParent 
[  33221]   WARN - inspections.IntellijLintClient - Incorrect detector reported disabled issue UselessParent 
[  33227]   WARN - inspections.IntellijLintClient - Incorrect detector reported disabled issue UselessParent 
[  33249]   WARN - inspections.IntellijLintClient - Incorrect detector reported disabled issue UselessParent 
[ 117873]   WARN - ConfigurableExtensionPointUtil - Can't find parent for project.propCompiler (Compiler) 
[ 128577]   WARN - api.vfs.impl.local.FileWatcher - Watcher terminated with exit code 0 
[   3975]  ERROR - llij.ide.plugins.PluginManager - com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: Window must not be zero [Plugin: com.wakatime.intellij.plugin] 
java.lang.RuntimeException: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: Window must not be zero [Plugin: com.wakatime.intellij.plugin]
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:178)
	at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:52)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:738)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:699)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:708)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: Window must not be zero [Plugin: com.wakatime.intellij.plugin]
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:245)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:39)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:590)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:610)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:125)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:359)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:116)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:87)
	at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:504)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:486)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:170)
	... 16 more
Caused by: com.intellij.diagnostic.PluginException: Window must not be zero [Plugin: com.wakatime.intellij.plugin]
	... 30 more
Caused by: java.lang.IllegalArgumentException: Window must not be zero
	at sun.awt.X11.WindowPropertyGetter.<init>(WindowPropertyGetter.java:56)
	at sun.awt.X11.WindowPropertyGetter.<init>(WindowPropertyGetter.java:73)
	at sun.awt.X11.XlibUtil.isToplevelWindow(XlibUtil.java:304)
	at sun.awt.X11.XWindowPeer.setToplevelTransientFor(XWindowPeer.java:1583)
	at sun.awt.X11.XWindowPeer.addToTransientFors(XWindowPeer.java:1697)
	at sun.awt.X11.XWindowPeer.setModalBlocked(XWindowPeer.java:1519)
	at sun.awt.X11.XDialogPeer.blockWindows(XDialogPeer.java:122)
	at java.awt.Dialog.blockWindows(Dialog.java:1576)
	at java.awt.Dialog.modalShow(Dialog.java:1453)
	at java.awt.Dialog.conditionalShow(Dialog.java:922)
	at java.awt.Dialog.show(Dialog.java:1043)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1614)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1571)
	at com.wakatime.intellij.plugin.ApiKey.promptForApiKey(ApiKey.java:61)
	at com.wakatime.intellij.plugin.WakaTime.initComponent(WakaTime.java:97)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:568)
	... 27 more
[   3977]  ERROR - llij.ide.plugins.PluginManager - Android Studio 1.2.1.1  Build #AI-141.1903250 
[   3977]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.7.0_75 
[   3977]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
[   3977]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation 
[   3977]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
[   3977]  ERROR - llij.ide.plugins.PluginManager - Last Action:  

Plugin Error: Plugin 'com.wakatime.intellij.plugin' failed to initialize and will be disabled.  Please restart Android Studio.

java.lang.IllegalArgumentException: Window must not be zero
	at sun.awt.X11.WindowPropertyGetter.<init>(WindowPropertyGetter.java:56)
	at sun.awt.X11.WindowPropertyGetter.<init>(WindowPropertyGetter.java:73)
	at sun.awt.X11.XlibUtil.isToplevelWindow(XlibUtil.java:304)
	at sun.awt.X11.XWindowPeer.setToplevelTransientFor(XWindowPeer.java:1583)
	at sun.awt.X11.XWindowPeer.addToTransientFors(XWindowPeer.java:1697)
	at sun.awt.X11.XWindowPeer.setModalBlocked(XWindowPeer.java:1519)
	at sun.awt.X11.XDialogPeer.blockWindows(XDialogPeer.java:122)
	at java.awt.Dialog.blockWindows(Dialog.java:1576)
	at java.awt.Dialog.modalShow(Dialog.java:1453)
	at java.awt.Dialog.conditionalShow(Dialog.java:922)
	at java.awt.Dialog.show(Dialog.java:1043)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1614)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1571)
	at com.wakatime.intellij.plugin.ApiKey.promptForApiKey(ApiKey.java:61)
	at com.wakatime.intellij.plugin.WakaTime.initComponent(WakaTime.java:97)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:568)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:610)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:125)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:359)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:116)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:87)
	at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:504)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:486)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:170)
	at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:52)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:738)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:699)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:708)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

Also, an UI exception occurred on attempt to show above message:
java.lang.IllegalArgumentException: Window must not be zero
	at sun.awt.X11.WindowPropertyGetter.<init>(WindowPropertyGetter.java:56)
	at sun.awt.X11.WindowPropertyGetter.<init>(WindowPropertyGetter.java:73)
	at sun.awt.X11.XlibUtil.isToplevelWindow(XlibUtil.java:304)
	at sun.awt.X11.XWindowPeer.setToplevelTransientFor(XWindowPeer.java:1583)
	at sun.awt.X11.XWindowPeer.updateTransientFor(XWindowPeer.java:1605)
	at sun.awt.X11.XWindowPeer.setModalBlocked(XWindowPeer.java:1536)
	at sun.awt.X11.XDialogPeer.blockWindows(XDialogPeer.java:122)
	at java.awt.Dialog.blockWindows(Dialog.java:1576)
	at java.awt.Dialog.modalShow(Dialog.java:1453)
	at java.awt.Dialog.conditionalShow(Dialog.java:922)
	at java.awt.Dialog.show(Dialog.java:1043)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:870)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:667)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:638)
	at com.intellij.idea.Main.showMessage(Main.java:249)
	at com.intellij.ide.plugins.PluginManager.processException(PluginManager.java:125)
	at com.intellij.ide.IdeEventQueue.processException(IdeEventQueue.java:403)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
dkzm@trau:~/android-studio/bin$  
dkzm@trau:~/android-studio/bin$ java -version
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~utopic1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
dkzm@trau:~/android-studio/bin$ uname -a
Linux trau 3.16.0-31-generic #41-Ubuntu SMP Tue Feb 10 15:24:04 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
dkzm@trau:~/android-studio/bin$ 
dkzm@trau:~/android-studio/bin$ cat /etc/issue
Ubuntu 14.10 \n \l

dkzm@trau:~/android-studio/bin$

**Comment by intari** [comment]
wakatime plugin installs correctly when I  switch to Plasma desktop (from regular Ubuntu one)

**Comment by alanhamlett** [comment]
Oh, good to know. I was looking into it as an OpenJDK problem. With the Plasma desktop, are you still using OpenJDK?
