### ISSUE TITLE
PHPStorm fatal error

### ISSUE THREAD

**Issue by dstockto** [wakatime/jetbrains-wakatime#42]
When I have an open project in phpstorm and then open a new one via command line (pstorm) I get a a notice that an error has happened. The error is this:

```
codeload.github.com
java.net.UnknownHostException: codeload.github.com
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:223)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:431)
	at java.net.Socket.connect(Socket.java:527)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:570)
	at com.sun.net.ssl.internal.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:141)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:163)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:424)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:538)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:276)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:172)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:923)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:158)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1195)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:234)
	at java.net.URL.openStream(URL.java:1010)
	at com.wakatime.intellij.plugin.Dependencies.installCLI(Dependencies.java:156)
	at com.wakatime.intellij.plugin.Dependencies.upgradeCLI(Dependencies.java:170)
	at com.wakatime.intellij.plugin.WakaTime$1$1.run(WakaTime.java:70)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:908)
	at com.wakatime.intellij.plugin.WakaTime$1.run(WakaTime.java:61)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

**Comment by alanhamlett** [comment]
Are you behind a proxy?

**Comment by dstockto** [comment]
Nope, no proxy.

**Comment by alanhamlett** [comment]
Are you connected to the internet when opening the new project?

**Comment by alanhamlett** [comment]
Solved in Slack chat. Was a temporary issue with GitHub.
