### ISSUE TITLE
javax.net.ssl.SSLException: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by MichaelHindley** [wakatime/jetbrains-wakatime#46]
Using the "font fixed" jdk for ubuntu results in these errors when trying to use WakaTime:

```
2015-07-31 13:34:54,281 [   3023]  ERROR -                       WakaTime - PhpStorm 9.0  Build #PS-141.1912 
2015-07-31 13:34:54,281 [   3023]  ERROR -                       WakaTime - JDK: 1.8.0-tuxjdk 
2015-07-31 13:34:54,281 [   3023]  ERROR -                       WakaTime - VM: OpenJDK 64-Bit Client VM 
2015-07-31 13:34:54,281 [   3023]  ERROR -                       WakaTime - Vendor: Oracle Corporation 
2015-07-31 13:34:54,281 [   3023]  ERROR -                       WakaTime - OS: Linux 

2015-07-31 13:34:59,821 [   8563]   WARN - dvertisement.PluginsAdvertiser - java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty 
javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```

**Comment by alanhamlett** [comment]
Just released v4.0.13 to fix this.

**Comment by luismagr** [comment]
I'm getting this error with PhpStorm 9.0.2 and Ubuntu 15.04. Any idea or suggestion? I have tried to pass to phpstorm.vmoptions the option -Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts but I'm still getting this error.

Thanks in advance

**Comment by alanhamlett** [comment]
Can you copy/paste the full traceback with line number for your error here?

**Comment by luismagr** [comment]
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=350m; support was removed in 8.0
[   1843]   WARN - om.intellij.util.ProfilingUtil - Profiling agent is not enabled. Add -agentlib:yjpagent to idea.vmoptions if necessary to profile IDEA. 
[   1910]  ERROR -                       WakaTime - java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty 
javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1906)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1889)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1410)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1038)
	at com.wakatime.intellij.plugin.Dependencies.downloadFile(Dependencies.java:241)
	at com.wakatime.intellij.plugin.Dependencies.installCLI(Dependencies.java:181)
	at com.wakatime.intellij.plugin.WakaTime$1.run(WakaTime.java:69)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:90)
	at sun.security.validator.Validator.getInstance(Validator.java:179)
	at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)
	at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1488)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	... 17 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
	at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
	at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:88)
	... 29 more
[   1912]  ERROR -                       WakaTime - PhpStorm 9.0.2  Build #PS-141.2462 
[   1912]  ERROR -                       WakaTime - JDK: 1.8.0_60 
[   1913]  ERROR -                       WakaTime - VM: Java HotSpot(TM) 64-Bit Server VM 
[   1913]  ERROR -                       WakaTime - Vendor: Oracle Corporation 
[   1913]  ERROR -                       WakaTime - OS: Linux 
[   1913]  ERROR -                       WakaTime - Last Action:  
[   8143]   WARN - api.vfs.impl.local.FileWatcher - Watcher terminated with exit code 0

**Comment by luismagr** [comment]
Also I have to say that i have tested with openjdk, jdk1.7_45 and jdk1.8_60 with the same results

**Comment by alanhamlett** [comment]
Is this fixed with v5.0.1?

**Comment by gandarez** [comment]
Is this still NOK?

**Comment by alanhamlett** [comment]
It's probably still a bug, but the code has changed a lot since then and it would help to have updated debug logs.

@luismagr can you copy/paste the error traceback again from your `idea.log` file if it's still occurring? Make sure to enable debug mode before triggering it.

**Comment by luismagr** [comment]
Hi,

Sorry, I can't help on this as It's been a long time without using wakatime so I'm not using the plugin.

Thanks for the time on this
