### ISSUE TITLE
Wakatime fails on PHPStorm after plugin update

### ISSUE THREAD

**Issue by asenseofdesign** [wakatime/jetbrains-wakatime#50]
Upon last update, wakatime fails on my PHPStorm. On initialization, it throws the error message pasted below:
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
Plugin 'com.wakatime.intellij.plugin' failed to initialize and will be disabled.  Please restart PhpStorm.

java.lang.NullPointerException
    at com.wakatime.intellij.plugin.Dependencies.getPythonFromRegistry(Dependencies.java:92)
    at com.wakatime.intellij.plugin.Dependencies.getPythonLocation(Dependencies.java:60)
    at com.wakatime.intellij.plugin.Dependencies.isPythonInstalled(Dependencies.java:34)
    at com.wakatime.intellij.plugin.WakaTime.initComponent(WakaTime.java:85)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:568)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:610)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:125)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:354)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:116)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:87)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:499)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:481)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:170)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:62)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
I also tried to uninstall and reinstall wakatime plugin.

More details about my configuration:
-  PHPStorm 9.0.2 Build #PS-141-2462 (latest available at this time)
- OS: Windows 8.1 Pro, 64 bit

**Comment by toptalo** [comment]
Same problem on Win10 + PhpStorm 8.0.3 Build 139.1348

**Comment by alanhamlett** [comment]
Should be fixed with v5.0.2.

**Comment by alanhamlett** [comment]
Sorry about this, I tested on Win 8.1 32bit. @toptalo are you also using 64bit Windows?

Version 5.0.2 prevents the exception, but still won't read the python binary path from the Windows registry.

**Comment by toptalo** [comment]
@alanhamlett, yes 64bit.

Update to 5.0.3 helps. Thanks a lot!

**Comment by asenseofdesign** [comment]
5.0.3 fixed it. Thank you very much!
