### ISSUE TITLE
com.intellij.diagnostic.PluginException: Argument for @NotNull parameter 'defaultValue'

### ISSUE THREAD

**Issue by nvlad** [wakatime/jetbrains-wakatime#82]
after update ".ignore" plugin from 1.6 to 1.7 version

error message
```
com.intellij.diagnostic.PluginException: Argument for @NotNull parameter 'defaultValue' of com/intellij/util/ObjectUtils.notNull must not be null [Plugin: mobi.hsz.idea.gitignore]
```

backtrace
```
com.intellij.diagnostic.PluginException: Argument for @NotNull parameter 'defaultValue' of com/intellij/util/ObjectUtils.notNull must not be null [Plugin: mobi.hsz.idea.gitignore]
com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: Argument for @NotNull parameter 'defaultValue' of com/intellij/util/ObjectUtils.notNull must not be null [Plugin: mobi.hsz.idea.gitignore]
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:249)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:519)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:125)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:109)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:285)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:245)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.d(ProjectManagerImpl.java:307)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:587)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:215)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.getDefaultProject(ProjectManagerImpl.java:304)
	at com.wakatime.intellij.plugin.WakaTime$3.run(WakaTime.java:153)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.diagnostic.PluginException: Argument for @NotNull parameter 'defaultValue' of com/intellij/util/ObjectUtils.notNull must not be null [Plugin: mobi.hsz.idea.gitignore]
	... 35 more
Caused by: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'defaultValue' of com/intellij/util/ObjectUtils.notNull must not be null
	at com.intellij.util.ObjectUtils.notNull(ObjectUtils.java)
	at com.intellij.util.ObjectUtils.notNull(ObjectUtils.java:74)
	at com.intellij.util.ObjectUtils.assertNotNull(ObjectUtils.java:35)
	at com.intellij.dvcs.repo.VcsRepositoryManager.getInstance(VcsRepositoryManager.java:61)
	at mobi.hsz.idea.gitignore.util.CacheMap.<init>(CacheMap.java:142)
	at mobi.hsz.idea.gitignore.IgnoreManager.<init>(IgnoreManager.java:282)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:478)
	... 32 more
```

**Comment by alanhamlett** [comment]
Fixed with v7.0.10.

**Comment by nvlad** [comment]
after update plugins, PhpStorm alert
error
```
com.intellij.diagnostic.PluginException: Argument for @NotNull parameter 'defaultValue' of com/intellij/util/ObjectUtils.notNull must not be null [Plugin: mobi.hsz.idea.gitignore]
```
stacktrace
```
com.intellij.diagnostic.PluginException: Argument for @NotNull parameter 'defaultValue' of com/intellij/util/ObjectUtils.notNull must not be null [Plugin: mobi.hsz.idea.gitignore]
com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: Argument for @NotNull parameter 'defaultValue' of com/intellij/util/ObjectUtils.notNull must not be null [Plugin: mobi.hsz.idea.gitignore]
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:249)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:519)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:125)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:109)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:285)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:245)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.d(ProjectManagerImpl.java:307)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:587)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:215)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.getDefaultProject(ProjectManagerImpl.java:304)
	at com.wakatime.intellij.plugin.WakaTime$3.run(WakaTime.java:156)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.diagnostic.PluginException: Argument for @NotNull parameter 'defaultValue' of com/intellij/util/ObjectUtils.notNull must not be null [Plugin: mobi.hsz.idea.gitignore]
	... 35 more
Caused by: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'defaultValue' of com/intellij/util/ObjectUtils.notNull must not be null
	at com.intellij.util.ObjectUtils.notNull(ObjectUtils.java)
	at com.intellij.util.ObjectUtils.notNull(ObjectUtils.java:74)
	at com.intellij.util.ObjectUtils.assertNotNull(ObjectUtils.java:35)
	at com.intellij.dvcs.repo.VcsRepositoryManager.getInstance(VcsRepositoryManager.java:61)
	at mobi.hsz.idea.gitignore.util.CacheMap.<init>(CacheMap.java:142)
	at mobi.hsz.idea.gitignore.IgnoreManager.<init>(IgnoreManager.java:282)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:478)
	... 32 more
```

**Comment by alanhamlett** [comment]
That error looks like it's coming from the `mobi.hsz.idea.gitignore` plugin, not WakaTime. Does the error still occur when you uninstall WakaTime?

**Comment by nvlad** [comment]
Thanks for the response! The problem was indeed in the plugin ".ignore", and has been fixed in the new version.

**Comment by alanhamlett** [comment]
Ok, thanks for the update!
