### ISSUE TITLE
PyCharm-wakatime caughts a connection error on my mac, while IntelliJ IEDA-wakatime works fine.

### ISSUE THREAD

**Issue by JooperGe** [wakatime/jetbrains-wakatime#92]
```
2017-11-19 09:34:02,765 [  82592]   WARN -                       WakaTime - Operation timed out (Connection timed out) 
java.net.ConnectException: Operation timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1045)
	at com.wakatime.intellij.plugin.Dependencies.getUrlAsString(Dependencies.java:309)
	at com.wakatime.intellij.plugin.Dependencies.latestCliVersion(Dependencies.java:175)
	at com.wakatime.intellij.plugin.Dependencies.isCLIOld(Dependencies.java:161)
	at com.wakatime.intellij.plugin.WakaTime$2.run(WakaTime.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-11-19 09:34:02,766 [  82593]   INFO -                       WakaTime - Upgrading wakatime-cli ... 
2017-11-19 09:34:11,204 [  91031]   INFO -                       WakaTime - Finished upgrading wakatime-cli. 
2017-11-19 09:36:08,304 [ 208131]   INFO - .script.IdeScriptEngineManager - javax.script.ScriptEngineManager initialized in 60 ms 
2017-11-19 09:36:12,731 [ 212558]  DEBUG -                       WakaTime - Logging level set to DEBUG 
2017-11-19 09:37:06,718 [ 266545]  DEBUG -                       WakaTime - Executing CLI: [pythonw, /Users/jooper/.wakatime/wakatime-master/wakatime/cli.py, --entity, /Users/jooper/Desktop/python/pyapp/main/chapter5/chapter5_practices.py, --time, 1511055419.4020, --key, XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXcef8, --project, pyapp, --language, Python, --plugin, Python/2017.2.4 Python-wakatime/9.0.1, --write] 
2017-11-19 09:37:11,239 [ 271066]  DEBUG -                       WakaTime - Command finished with return value: 0 
2017-11-19 09:37:40,517 [ 300344]  ERROR - jediterm.terminal.TerminalMode - Mode EightBitInput is not implemented, setting to true 
2017-11-19 09:37:46,716 [ 306543]  DEBUG -                       WakaTime - Executing CLI: [pythonw, /Users/jooper/.wakatime/wakatime-master/wakatime/cli.py, --entity, /Users/jooper/Desktop/python/pyapp/main/chapter5/chapter5_practices.py, --time, 1511055459.8240, --key, XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXcef8, --project, pyapp, --language, Python, --plugin, Python/2017.2.4 Python-wakatime/9.0.1, --write] 
2017-11-19 09:37:50,210 [ 310037]  DEBUG -                       WakaTime - Command finished with return value: 0 
2017-11-19 09:37:56,717 [ 316544]  DEBUG -                       WakaTime - Executing CLI: [pythonw, /Users/jooper/.wakatime/wakatime-master/wakatime/cli.py, --entity, /Users/jooper/Desktop/python/pyapp/main/chapter5/chapter5_practices.py, --time, 1511055475.4840, --key, XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXcef8, --project, pyapp, --language, Python, --plugin, Python/2017.2.4 Python-wakatime/9.0.1, --write] 
2017-11-19 09:38:01,131 [ 320958]  DEBUG -                       WakaTime - Command finished with return value: 0 
2017-11-19 09:38:46,719 [ 366546]  DEBUG -                       WakaTime - Executing CLI: [pythonw, /Users/jooper/.wakatime/wakatime-master/wakatime/cli.py, --entity, /Users/jooper/Desktop/python/pyapp/main/chapter5/chapter5_practices.py, --time, 1511055522.0230, --key, XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXcef8, --project, pyapp, --language, Python, --plugin, Python/2017.2.4 Python-wakatime/9.0.1, --write] 
2017-11-19 09:38:50,194 [ 370021]  DEBUG -                       WakaTime - Command finished with return value: 0 
```

**Comment by gandarez** [comment]
Is this still NOK @alanhamlett?

**Comment by alanhamlett** [comment]
Let's close this since it's from the legacy Python wakatime-cli that's no longer used.
